### ISSUE TITLE
Add support for 11PR38120RGBWH1

### ISSUE THREAD

**Issue by kerberjc** [jdeath/Hubspace-Homeassistant#10]
Include simple fix to add support for new model 11PR38120RGBWH1:

light.py
179:  if self._model == '50291, 50292' or self._model == '11PR38120RGBWH1':

Model information: https://www.homedepot.com/p/EcoSmart-120-Watt-Equivalent-Smart-Hubspace-PAR38-Color-Changing-CEC-LED-Light-Bulb-with-Voice-Control-1-Bulb-11PR38120RGBWH1/318411934

**Comment by jdeath** [comment]
Thanks. I added to master, will push a release in a couple days
