### ISSUE TITLE
Fails after latest updates

### ISSUE THREAD

**Issue by joeinaustin** [jdeath/Hubspace-Homeassistant#105]
My hubspace integration was working fine for a month or so after I first loaded it.  At some point it stopped working and I just noticed it was not working.  I have updated several other HA components since it was first working.  I tried deleting hubspace and re-downloading it.  No difference.  It just fails with the same error which I cannot decipher.

"Setup failed for custom integration 'hubspace': Requirements for hubspace not found: ['aiofiles==24.1.0']."

I am running latest updated HA on a dedicated PC.  Any ideas?

**Comment by joeinaustin** [comment]
Btw, I only have one device.  It is a lock.  I don't see many references to locks in he docs.  If more info is needed, let me know what, and how to get it.  The logs I found seemed pretty limited.

**Comment by joeinaustin** [comment]
I resolved it by updating to yesterdays HA update, completely deleting everything including the entities. and reinstalling.

**Comment by joeinaustin** [comment]
I resolved it by updating to yesterdays HA update, completely deleting everything including the entities. and reinstalling.

**Comment by Expl0dingBanana** [comment]
Sorry I didnt get around to this! Im glad updating HA solved your issue.
