### ISSUE TITLE
Wrong Entity

### ISSUE THREAD

**Issue by Bentley0227** [jdeath/Hubspace-Homeassistant#106]
I have 3 Ecosmart AL-TP-RGBW-16FT that only have a Wifi-rssi Entity but they are RGBW led light strips.  They used to work before the update.  Let me know what else I can add to help.  Thanks.
[_dump_hs_raw.json](https://github.com/user-attachments/files/17143849/_dump_hs_raw.json)
[_dump_hs_devices.json](https://github.com/user-attachments/files/17143851/_dump_hs_devices.json)
[home-assistant_hubspace_2024-09-26T06-20-48.818Z.log](https://github.com/user-attachments/files/17143854/home-assistant_hubspace_2024-09-26T06-20-48.818Z.log)

**Comment by Expl0dingBanana** [comment]
The traceback looks like its trying to do something with color temperature. Let me see what its doing.

**Comment by Expl0dingBanana** [comment]
Please run the following to test the fix:

 * Goto HACS within HA
 * Click `Hubspace-HomeAssistant`
 * Click the triple dots on the top-left
 * Click `Update Information`
 *  Click the triple dots on the top-left
 * Click `Redownload`
 * Click `Show beta versions`
 * Select `fix-color-temp-identifer`  (apparently I couldnt spell this morning)
 * Click `DOWNLOAD`
 * Restart HA

**Comment by Bentley0227** [comment]
I did that but I still don't have a Control entity. The three devices show up but the only entity they have is diagnostic. I have no way of controlling them.

**Comment by Expl0dingBanana** [comment]
Can you confirm you switched to the release `fix-color-temp-identifer` and restarted HA? After switching to the dev release I see the following for your devices:
![image](https://github.com/user-attachments/assets/950fa29d-f786-4e4e-8e27-dbbc097d04c2)



Prior to the code change:
![image](https://github.com/user-attachments/assets/2936aab1-bfc2-4600-90ac-c8a1797e5ec5)

**Comment by Bentley0227** [comment]
Yes, I just re-downloaded it and re-started again. This is what I see. ![image](https://github.com/user-attachments/assets/92ccbc9e-693e-40c3-93f4-e91c0307a78a)![image](https://github.com/user-attachments/assets/b81a4fb9-d1d5-4025-8cfc-02bb67154c58)![image](https://github.com/user-attachments/assets/ef764599-e7cc-468f-aebc-c7b9aea7c7c6)

**Comment by Expl0dingBanana** [comment]
Can you upload the HA logs? I'll review to see what's going on

**Comment by Bentley0227** [comment]
[_dump_hs_raw (1).json](https://github.com/user-attachments/files/17177114/_dump_hs_raw.1.json)
[_dump_hs_devices (1).json](https://github.com/user-attachments/files/17177115/_dump_hs_devices.1.json)
[home-assistant_hubspace_2024-09-29T01-03-09.641Z.log](https://github.com/user-attachments/files/17177116/home-assistant_hubspace_2024-09-29T01-03-09.641Z.log)

**Comment by Expl0dingBanana** [comment]
After reviewing the logs I believe HA was never restarted after pulling the
update as previous messages are in the log. Please restart HA and let me
know if this fixes the issue.

**Comment by Bentley0227** [comment]
I had restart multiple times. I even installed the custom software again. I just power cycled HA and it still looks the same. No change.

**Comment by Expl0dingBanana** [comment]
Can you provide logs for me to review?

**Comment by Bentley0227** [comment]
[_dump_hs_raw.json](https://github.com/user-attachments/files/17181471/_dump_hs_raw.json)
[_dump_hs_devices.json](https://github.com/user-attachments/files/17181472/_dump_hs_devices.json)
I just re-downloaded it and installed it and re-started.  Still no luck.

**Comment by Expl0dingBanana** [comment]
Can you provide the HA logs? There's probably a traceback somewhere

**Comment by Bentley0227** [comment]
[home-assistant.log](https://github.com/user-attachments/files/17181488/home-assistant.log)
[home-assistant1.log](https://github.com/user-attachments/files/17181491/home-assistant1.log)
These?

**Comment by Expl0dingBanana** [comment]
Yup, those! Apparently at some point I `git`'d wrong and lost some changes. Let me take another whack at this.

**Comment by Bentley0227** [comment]
No worries!  Thanks for all the help!

**Comment by Expl0dingBanana** [comment]
Please download 3.2.0 and restart HA and let me know if the issue persists. It is now the latest release.  If it does not solve your issue please post the logs!

**Comment by Bentley0227** [comment]
Winner!!! Works as expected now. Thank you!!
