### ISSUE TITLE
Support for freezer device type

### ISSUE THREAD

**Issue by Bad-Magic** [jdeath/Hubspace-Homeassistant#109]
Looks like my new freezer isn't a supported device type.  I've attached the device json returned from the API.

Would love to be able to alert on temperature.   We just had a compressor failure and lost an entire freezer of food. :(
[hubspace.zip](https://github.com/user-attachments/files/17532007/hubspace.zip)

**Comment by Expl0dingBanana** [comment]
Oof that sucks. I had that happen recently and re-buying an whole freezer worth of stuff isnt fun. Let me take a look at the dump and get something out.

**Comment by Expl0dingBanana** [comment]
@Bad-Magic I am reviewing the dump and a bit confused on the "climate" control portion of functionality. Can you validate or fix these ideas?

Fridge - This looks like 1-10 scale. Is this how the fridge is configured where you can only select a number and not a specific temperature?
Freezer - Does this go between -24F and -12F?

**Comment by Bad-Magic** [comment]
Freezer is -11 to +10 F.
Cool is 34 to 50F
![IMG_6237](https://github.com/user-attachments/assets/5bb13847-f6b7-4721-9c3c-1f591858f251)
![IMG_6238](https://github.com/user-attachments/assets/765d98a0-3d10-4d2e-903e-53412b1fe3f6)

**Comment by Expl0dingBanana** [comment]
ah sweet, they have some magic going on!

Fridge:
```json

            {
                "id": "6a78ae35-4750-450e-bbce-515a4b6aa14d",
                "createdTimestampMs": 1713308853739,
                "updatedTimestampMs": 1713308853739,
                "functionClass": "temperature",
                "functionInstance": "fridge-target",
                "type": "numeric",
                "schedulable": false,
                "values": [
                    {
                        "id": "33d60fcb-2718-4cfc-a7a8-eb89958abc05",
                        "createdTimestampMs": 1713308853750,
                        "updatedTimestampMs": 1713308853750,
                        "name": "fridge-target",
                        "deviceValues": [
                            {
                                "id": "a8a57bb0-1367-4a48-9f1e-0b9bbd302879",
                                "createdTimestampMs": 1713308853762,
                                "updatedTimestampMs": 1713308853762,
                                "type": "attribute",
                                "key": "10"
                            }
                        ],
                        "range": {
                            "min": 1.0,
                            "max": 10.0,
                            "step": 1.0
                        }
                    }
                ]
            },
 ```

Freezer:
```json

            {
                "id": "23212230-205f-4f79-b53f-7ca7fd250fa8",
                "createdTimestampMs": 1713308853770,
                "updatedTimestampMs": 1713308853770,
                "functionClass": "temperature",
                "functionInstance": "freezer-target",
                "type": "numeric",
                "schedulable": false,
                "values": [
                    {
                        "id": "b7858eff-fce9-4dbf-92ad-0f2b9c1753c9",
                        "createdTimestampMs": 1713308853788,
                        "updatedTimestampMs": 1713308853788,
                        "name": "freezer-target",
                        "deviceValues": [
                            {
                                "id": "e769aaea-bb7d-41df-9645-629febf5cb5a",
                                "createdTimestampMs": 1713308853800,
                                "updatedTimestampMs": 1713308853800,
                                "type": "attribute",
                                "key": "11"
                            }
                        ],
                        "range": {
                            "min": -24.0,
                            "max": -12.0,
                            "step": 1.0
                        }
                    }
                ]
            },
```

**Comment by Expl0dingBanana** [comment]
Upon reviewing the dump some more (and partial implementation), it never reports the current temperature, just what the target temp is. I think this device will be binary sensors + number (I have no idea on this but it may work). That way you can adjust the temperature and see if its alerting.

**Comment by Bad-Magic** [comment]
No temperature sensor? Boo. 

Let me know how I can help test or debug. Happy to make the time.

**Comment by Expl0dingBanana** [comment]
@Bad-Magic Did you want to be able to set the temp, or are you more concerned with seeing alerts? I modified the data so MCU would should as problematic for the screenshot.
![image](https://github.com/user-attachments/assets/715f8e26-280e-463c-a75a-33393fd0abbe)

**Comment by Bad-Magic** [comment]
I don’t think I would ever care to adjust the temperature. I really only want alerts if something has gone awry.

**Comment by Expl0dingBanana** [comment]
Add freezer diagnostics to HA

 * Goto HACS within HA
 * Click `Hubspace-HomeAssistant`
 * Click the triple dots on the top-left
 * Click `Update Information`
 *  Click the triple dots on the top-left
 * Click `Redownload`
 * Click `Show beta versions`
 * Select `dev-freezer`
 * Click `DOWNLOAD`
 * Restart HA


Let me know if anything doesnt work or you want something modified

**Comment by Expl0dingBanana** [comment]
@Bad-Magic Did the beta version solve your issue?

**Comment by Bad-Magic** [comment]
Entities show up.  Logs look clean.  I'm not going to trigger an overtemp given I filled it with food. 
<img width="1154" alt="image" src="https://github.com/user-attachments/assets/51ffba1f-762d-47e6-9368-a1c8f7d17973">

Anything else you want me to poke at?

**Comment by Expl0dingBanana** [comment]
Nope, perfect! I will get this merged to main

**Comment by Expl0dingBanana** [comment]
@Bad-Magic Can you review this issue and see if I am missing anything with the fridge / freezer?
