### ISSUE TITLE
Support for outlets

### ISSUE THREAD

**Issue by krozgrov** [jdeath/Hubspace-Homeassistant#11]
Does this custom plugin support subspace smart outlets if so is there a example configuration.yaml?

**Comment by jdeath** [comment]
In the readme: Outlets (HPKA315CWB) work with on/off on both outputs. Single outlet (HPPA51CWB and HPPA11AWBA023) models handled correctly. 

If your outlet is not supported, it can be added by following instructions in the readme

**Comment by krozgrov** [comment]
I have a HPKA315CWB

light:
  - platform: hubspace
    username: 
    password: 
    debug: true
    friendlynames:
      - 'Outlet1'
      - 'Outlet2'

In Home Assistant I'm seeing the following error message.
Logger: homeassistant.components.light
Source: custom_components/hubspace/light.py:100 
Integration: Light (documentation, issues) 
First occurred: 7:01:20 AM (1 occurrences) 
Last logged: 7:01:20 AM

Error while setting up hubspace platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hubspace/light.py", line 100, in setup_platform
    _LOGGER.debug("Switch on Model " + model )
TypeError: can only concatenate str (not "NoneType") to str

**Comment by jdeath** [comment]
Looks like you fixed it. You just pass the friendly name of the device itself, not what you named each outlet. It will automatically make an freindlyname_outlet_1 and freindlyname_outlet_2 entity

**Comment by krozgrov** [comment]
I updated my yaml

#HubSpace Config
light:
  - platform: hubspace
    username:
    password:
    debug: true
    friendlynames:
      - ‘Garage_Outlet'

But still get this error
Logger: homeassistant.components.light
Source: custom_components/hubspace/light.py:100
Integration: Light (documentation, issues)
First occurred: 7:46:20 AM (1 occurrences)
Last logged: 7:46:20 AM

Error while setting up hubspace platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hubspace/light.py", line 100, in setup_platform
    _LOGGER.debug("Switch on Model " + model )
TypeError: can only concatenate str (not "NoneType") to str


On Oct 29, 2022, at 7:35 AM, jdeath ***@***.***> wrote:



Looks like you fixed it. You just pass the friendly name of the device itself, not what you named each outlet. It will automatically make an freindlyname_outlet_1 and freindlyname_outlet_2 entity

**Comment by jdeath** [comment]
yaml looks ok. Try this.
edit \\homeassistant\\config\custom_components\hubspace.py
There will be a function  def getChildId(self,deviceName):
remove all the # in front of each line to get extra debugging

Also in your homeassistant configuration.yaml, we need to enable more debuggin. You may have a logger: entry, so just make it look like below
```
logger:
  default: error
  logs:
    custom_components.hubspace: debug
```
Now the logs should give us more information.

**Comment by krozgrov** [comment]
2022-10-29 08:17:40.855 DEBUG (SyncWorker_3) [custom_components.hubspace.hubspace] token 38160983-b375-4f15-a792-53cf24ce49ee
2022-10-29 08:17:41.121 DEBUG (SyncWorker_3) [custom_components.hubspace.hubspace] ############ Dumping all info 1 0f 2 #########
2022-10-29 08:17:41.124 DEBUG (SyncWorker_3) [custom_components.hubspace.hubspace] [
{
"children": [
"04cdf279-c22f-4270-b342-5b48432948ef",
"d33bd19a-081c-4663-b599-0f4848dbda2c"
],
"createdTimestampMs": 0,
"friendlyName": "Home",
"id": "477b13df-b2a3-4890-82ab-39522ec7eaa0",
"locale": "en_US",
"typeId": "metadevice.home",
"updatedTimestampMs": 0,
"version": 1
},
{
"children": [
"d33bd19a-081c-4663-b599-0f4848dbda2c"
],
"createdTimestampMs": 0,
"friendlyDescription": "",
"friendlyName": "Garage",
"id": "04cdf279-c22f-4270-b342-5b48432948ef",
"image": "wallpaper07.jpg",
"locale": "en_US",
"tag": "",
"typeId": "metadevice.room",
"updatedTimestampMs": 0,
"version": 1
},
{
"children": [],
"createdTimestampMs": 0,
"description": {
"createdTimestampMs": 1606272276217,
"defaultImage": "smart-outlet",
"descriptions": [],
"device": {
"defaultName": "Outlet",
"deviceClass": "power-outlet",
"manufacturerName": "Commercial Electric",
"model": "HPKA315CWB",
"profileId": "4e732283-f51f-4711-8f96-5a44a747fb55",
"type": "device"
},
"functions": [
{
"createdTimestampMs": 1606272276546,
"functionClass": "toggle",
"functionInstance": "outlet-2",
"id": "4f79ab66-9b6a-4176-bb28-10723a04227b",
"schedulable": true,
"type": "category",
"updatedTimestampMs": 1606272276546,
"values": [
{
"createdTimestampMs": 1606272276635,
"deviceValues": [
{
"createdTimestampMs": 1606272276665,
"id": "9d973bfb-2df8-4da0-b64c-982e0f42d5b3",
"key": "3",
"type": "attribute",
"updatedTimestampMs": 1606272276665,
"value": "1"
}
],
"id": "a353e336-b57f-4862-80a0-1d01900230ff",
"name": "on",
"range": {},
"updatedTimestampMs": 1606272276635
},
{
"createdTimestampMs": 1606272276576,
"deviceValues": [
{
"createdTimestampMs": 1606272276610,
"id": "d8393f15-748a-48c0-9fe8-02155b7c783a",
"key": "3",
"type": "attribute",
"updatedTimestampMs": 1606272276610,
"value": "0"
}
],
"id": "7891f4ce-bd19-4db8-90be-41b3b9d71239",
"name": "off",
"range": {},
"updatedTimestampMs": 1606272276576
}
]
},
{
"createdTimestampMs": 1606272276238,
"functionClass": "power",
"id": "a08ee642-7240-4330-9530-a4d20c30e629",
"schedulable": true,
"type": "category",
"updatedTimestampMs": 1606272276238,
"values": [
{
"createdTimestampMs": 1606272276344,
"deviceValues": [
{
"createdTimestampMs": 1606272276376,
"id": "b5b659a1-c6ab-45a9-b508-9ef06b8df3f6",
"key": "1",
"type": "attribute",
"updatedTimestampMs": 1606272276376,
"value": "1"
}
],
"id": "979cc7c0-ab01-4f7a-96ec-506b3369e465",
"name": "on",
"range": {},
"updatedTimestampMs": 1606272276344
},
{
"createdTimestampMs": 1606272276283,
"deviceValues": [
{
"createdTimestampMs": 1606272276316,
"id": "5f244ce7-6634-4d95-9eab-7b5e1979558c",
"key": "1",
"type": "attribute",
"updatedTimestampMs": 1606272276316,
"value": "0"
}
],
"id": "b0710ece-6a06-46c6-b0b7-2fbb49766a59",
"name": "off",
"range": {},
"updatedTimestampMs": 1606272276283
}
]
},
{
"createdTimestampMs": 1606272276777,
"functionClass": "timer",
"functionInstance": "outlet-2",
"id": "79462cf1-22e9-4862-8103-6972c32b8f22",
"schedulable": false,
"type": "numeric",
"updatedTimestampMs": 1606272276777,
"values": [
{
"createdTimestampMs": 1606272276806,
"deviceValues": [
{
"createdTimestampMs": 1606272276834,
"id": "ad5f6f46-0ef1-47d2-967b-2f78fdb466c5",
"key": "51",
"type": "attribute",
"updatedTimestampMs": 1606272276834
}
],
"id": "fa6680b7-195e-4156-b0fa-934e0321df3e",
"name": "timer-2",
"range": {
"max": 1440,
"min": 0,
"step": 1
},
"updatedTimestampMs": 1606272276806
}
]
},
{
"createdTimestampMs": 1606272276691,
"functionClass": "timer",
"functionInstance": "outlet-1",
"id": "109fb87d-4757-4dc5-838f-775d8d9efb5e",
"schedulable": false,
"type": "numeric",
"updatedTimestampMs": 1606272276691,
"values": [
{
"createdTimestampMs": 1606272276721,
"deviceValues": [
{
"createdTimestampMs": 1606272276751,
"id": "8ae861c0-5ad1-42b8-8f68-e2c04a8d2f25",
"key": "50",
"type": "attribute",
"updatedTimestampMs": 1606272276751
}
],
"id": "00fbc0f9-5946-4ad7-bc66-8027de8a9eda",
"name": "timer-1",
"range": {
"max": 1440,
"min": 0,
"step": 1
},
"updatedTimestampMs": 1606272276721
}
]
},
{
"createdTimestampMs": 1606272276403,
"functionClass": "toggle",
"functionInstance": "outlet-1",
"id": "debc966f-370e-4259-a3fb-4263254cdf50",
"schedulable": true,
"type": "category",
"updatedTimestampMs": 1606272276403,
"values": [
{
"createdTimestampMs": 1606272276433,
"deviceValues": [
{
"createdTimestampMs": 1606272276465,
"id": "30bb33e4-f341-4f45-b214-20200002087f",
"key": "2",
"type": "attribute",
"updatedTimestampMs": 1606272276465,
"value": "0"
}
],
"id": "0d62b185-f230-4885-a625-1400541362dd",
"name": "off",
"range": {},
"updatedTimestampMs": 1606272276433
},
{
"createdTimestampMs": 1606272276491,
"deviceValues": [
{
"createdTimestampMs": 1606272276521,
"id": "ff87fcba-667e-4f50-8742-b1aa3cefdd0c",
"key": "2",
"type": "attribute",
"updatedTimestampMs": 1606272276521,
"value": "1"
}
],
"id": "9b4e0cce-d9a7-4e9a-8c57-7165357dbf3e",
"name": "on",
"range": {},
"updatedTimestampMs": 1606272276491
}
]
}
],
"hints": [],
"id": "9b7a738a-0e6d-4f64-a8bb-a97e273f2447",
"updatedTimestampMs": 1606272276217,
"version": 1
},
"deviceId": "864ce0e2e6fe29b6",
"friendlyDescription": "",
"friendlyName": "WestOutlet",
"id": "d33bd19a-081c-4663-b599-0f4848dbda2c",
"image": "",
"locale": "en_US",
"state": {
"metadeviceId": "d33bd19a-081c-4663-b599-0f4848dbda2c",
"values": [
{
"functionClass": "toggle",
"functionInstance": "outlet-2",
"lastUpdateTime": 1667008833872,
"value": "off"
},
{
"functionClass": "power",
"lastUpdateTime": 1667008834009,
"value": "off"
},
{
"functionClass": "timer",
"functionInstance": "outlet-2",
"lastUpdateTime": 1666342651823,
"value": 0
},
{
"functionClass": "timer",
"functionInstance": "outlet-1",
"lastUpdateTime": 1666342651770,
"value": 0
},
{
"functionClass": "toggle",
"functionInstance": "outlet-1",
"lastUpdateTime": 1667008832389,
"value": "off"
},
{
"functionClass": "wifi-ssid",
"lastUpdateTime": 1666342652701,
"value": "Cosgrove's Castle"
},
{
"functionClass": "wifi-rssi",
"lastUpdateTime": 1666342652750,
"value": -48
},
{
"functionClass": "wifi-steady-state",
"lastUpdateTime": 1666342652813,
"value": "connected"
},
{
"functionClass": "wifi-setup-state",
"lastUpdateTime": 1666342652859,
"value": "connected"
},
{
"functionClass": "wifi-mac-address",
"lastUpdateTime": 0,
"value": "e0e2e6fe29b4"
},
{
"functionClass": "geo-coordinates",
"functionInstance": "system-device-location",
"lastUpdateTime": 1666342653148,
"value": {
"geo-coordinates": {
"latitude": "42.89865112304688",
"longitude": "-84.35823059082031"
}
}
},
{
"functionClass": "scheduler-flags",
"lastUpdateTime": 1666342651921,
"value": 0
},
{
"functionClass": "available",
"lastUpdateTime": 1666974702975,
"value": true
},
{
"functionClass": "visible",
"lastUpdateTime": 1666974702975,
"value": true
},
{
"functionClass": "direct",
"lastUpdateTime": 1666974702975,
"value": true
},
{
"functionClass": "ble-mac-address",
"lastUpdateTime": 0,
"value": "e0e2e6fe29b6"
}
]
},
"tag": "",
"typeId": "metadevice.device",
"updatedTimestampMs": 0,
"version": 1
}
]
2022-10-29 08:17:41.124 DEBUG (SyncWorker_3) [custom_components.hubspace.hubspace] ############ End Dump #########
2022-10-29 08:17:41.130 DEBUG (SyncWorker_3) [custom_components.hubspace.hubspace] No model found
2022-10-29 08:17:41.362 ERROR (MainThread) [homeassistant.components.light] Error while setting up hubspace platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/hubspace/light.py", line 100, in setup_platform
_LOGGER.debug("Switch on Model " + model )
TypeError: can only concatenate str (not "NoneType") to str

On Oct 29, 2022, at 8:03 AM, jdeath ***@***.***> wrote:



yaml looks ok. Try this.
edit \homeassistant\config\custom_components\hubspace.py
There will be a function def getChildId(self,deviceName):
remove all the # in front of each line to get extra debugging

Also in your homeassistant configuration.yaml, we need to enable more debuggin. You may have a logger: entry, so just make it look like below

logger:
  default: error
  logs:
    custom_components.hubspace: debug


Now the logs should give us more information.

**Comment by jdeath** [comment]
Your freindlyname is: WestOutlet 

try that. Is that not what it is named in the app?

**Comment by krozgrov** [comment]
Yep - that fixed it sir!  So I need to update the name of the outlet in the app and update the configuration.yaml to match that name.  I was using "Garage" as the friendlyname in the yaml because that was the room I had created in the app.

**Comment by jdeath** [comment]
Yes, they need to match. You can use the roomname instead of freindlyname, but again must match exactly. Someone added that capability, but I cannot help if it doesnt work
```
roomnames:
      - 'BoysRoom' (the name of your room as shown in the app)
```
