### ISSUE TITLE
Change name of wall plug will break devices when adding a new device and renaming others 

### ISSUE THREAD

**Issue by MattMcIntosh119** [jdeath/Hubspace-Homeassistant#112]
I had two working plugs, I added a third, and renamed first two. When I used add device in home assistant I got uniq I’d error, then all devices got removed when I tried a second time.

**Comment by jdeath** [comment]
Did you rename the home assistant entity or rename the device in the hubspace app? The latest version of homeassistant has been throwing unique_id errors for some strange reason.

Try to disable to integration, restart home assistant, remove any hubspace entities (in Settings->Device & Services -> Entities Tab At Top -> Search for "hubspace" . Click the gear, then click deleate

Enable the integration and see if they come back

The entities sometimes get added, but with a _2  as well.

**Comment by MattMcIntosh119** [comment]
ok, so i changed them in the hubspace .. that is what broke things.. 

Based on what you said, I disabled the integration, then removed it. (there was no entities showing), rebooted home assistant, installed hubspace intergration, put in account and password, and it added everything with new names and worked. 

It would appear that is you change in hubspace the name and ask it to login to hubspace again, it breaks things. If I has just done it and waited maybe it would have added new plugs and changed names.

**Comment by MattMcIntosh119** [comment]
Thank you!
