### ISSUE TITLE
Can not add integration to Home Assistant

### ISSUE THREAD

**Issue by TheAceMan** [jdeath/Hubspace-Homeassistant#116]
I am running Home Assistant in a kubernetes cluster and having issues with this custom component. I do have other custom components that working, but may be some configuration or permissions on my end.

When I select Add Integration and select hubspace, I get a brief dialog box stating "Please wait, starting configuration wizard for Hubspace". Then I get an error dialog stating "Config flow could not be loaded: {"message":"Invalid handler specified"}" and this is in the logs:

```
2024-12-02 17:14:57.315 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration hubspace: No module named 'hubspace_async'
```

Running the latest version of Home Assistant Core 2024.11.3 and running the current v3.3.0 of Hubspace-Homeassistant.

Also I do see a hubspace_async and hubspace_async-0.4.1.dist-info folder in my /config/deps folder for HA.

**Comment by MUSTARDTIGERFPV** [comment]
I have the exact same configuration and I'm experiencing the same issue. Running `pip install hubspace_async` inside my pod seemed to fix it up.

**Comment by Expl0dingBanana** [comment]
What versions of HACS are yall running?

**Comment by TheAceMan** [comment]
> I have the exact same configuration and I'm experiencing the same issue. Running `pip install hubspace_async` inside my pod seemed to fix it up.

@MUSTARDTIGERFPV Does this survive a pod restart or redeploy? Will look into this

@Expl0dingBanana Not running HACS, deploying container on Kubernetes with core HA.

**Comment by MUSTARDTIGERFPV** [comment]
It doesn't survive a reboot no - either it'll need to be fixed in another way, or you could bodge it with an initContainer or commands on the podSpec.

**Comment by Expl0dingBanana** [comment]
I am not familiar with this deployment type. Do other custom plugins that
require additional dependencies still work? HACS does dependency management
through what's defined in the manifest file. Without HACS, custom
dependencies aren't brought in

**Comment by TheAceMan** [comment]
Dug a bit deeper and found this issue:

https://github.com/home-assistant/core/issues/127966

As mentioned I see that the requirement creates hubspace_async and hubspace_async-0.4.1.dist-info folder in my /config/deps folder.

But it appears that these should be in /config/deps/lib/python3.12/site-packages, after copying the folders to this location it brings up the integration configuration UI as expected. Have not completed setup yet but got a step further.
