### ISSUE TITLE
installing, new to HA

### ISSUE THREAD

**Issue by xgaibtcgd** [jdeath/Hubspace-Homeassistant#12]
Hello,

Runnning home assistant core, trying to install this and follow along but i'm very new to home assistant.  I do have the core version and using to edit the files using Studio Code Server.  Here is how my config looks:

Error:  
`Failed to restart Home Assistant
The system cannot restart because the configuration is not valid: Invalid config for [light.hubspace]: invalid boolean value true - 'fence side' - 'house side' for dictionary value @ data['debug']. Got "true - 'Fence Side' - 'House Side'". (See ?, line ?).`

Configuration:
`
# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: "0000"
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

      
frontend:
  themes: !include_dir_merge_named themes

light:
  - platform: hubspace
    username: my@email.com
    password: Password123
    debug: true
      - 'Fence Side'
      - 'House Side'
    roomnames:
      - 'Front Yard'

**Comment by jdeath** [comment]
Probably better to post on home assistant thread, versus an issue here. More people can help you there. Also best if you use the <> button so the formatting is correct. Looks like you are missing the friendlyname tag

You can use a mix of freindlynames and roomnames, but I just use frieindlynames. The friendlyname is how the device shows up in your app. 
```
light:
  - platform: hubspace
    username: your_hubspace_username 
    password: your_hubspace_password
    debug: true 
    friendlynames:
      - 'Fence Side' 
      - 'House Side'
      - 'Front Yard'
```

**Comment by xgaibtcgd** [comment]
Thanks, not sure how i missed that but it fixed the config and was able to test things...  during that, i'm trying to turn the landscape transformer on/off and getting this error:

`2022-10-30 06:08:13.156 ERROR (MainThread) [homeassistant.components.light] Error while setting up hubspace platform for light
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
await asyncio.shield(task)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/hubspace/light.py", line 100, in setup_platform
_LOGGER.debug("Switch on Model " + model )
TypeError: can only concatenate str (not "NoneType") to str`

Didn't see anythinig else in the logs to do with hubspace

I had not defined anywhere a specific model and couldn't see anything that required that but the low voltage landscape transformer model is:  

Model # HB-200-1215WIFI
Bootloader: 2.3.1.231449-esp32
Application:: 2.3.1.23410-plug
Product Description 1.0.33

Thanks!

**Comment by jdeath** [comment]
That model is supported, the integration figures it out automatically. You did not set the freindlyname correctly. It must be *exactly* as shown in the app under Product Name. As the readme states, you only add the name of the parent device, not the 3 individual transformer outlets. The integration will create entities called: freindlyname_transformer_1 _2 _3 , 

If you have suggestions on how to make the documentation clearer, let me know.

**Comment by xgaibtcgd** [comment]
thanks, the documentation seems fine, i'm just new -- for example, i only found out yesterday that spaces in yaml files matter :)  anyways,  just wanted to update you that I got this all working now ...  thanks again for the assistance.
