### ISSUE TITLE
Plug Support

### ISSUE THREAD

**Issue by fischgeek** [jdeath/Hubspace-Homeassistant#15]
Wondering if you have a way to support a plug for me. But first, I should mention that I can't seem to get this working by following your instructions. The only thing I can think of is the plug isn't supported. My model number is `HPPA11CWB`

**Comment by jdeath** [comment]
I just updated the light.py in the repository for that model. Hopefully it will work if it outlet works like other versions. Download the raw file from github, replace your light.py in custom_components/hubspace/ and restart hubassistant. let me know if it works

**Comment by fischgeek** [comment]
Worked great! Thanks!
