### ISSUE TITLE
Implement Config Flow

### ISSUE THREAD

**Issue by dloveall** [jdeath/Hubspace-Homeassistant#18]
Per https://github.com/home-assistant/architecture/blob/master/adr/0010-integration-configuration.md#decision integrations that communicate with devices are only to be configured via the UI.

Adding an issue to track discuss and track changes required to support.

I believe the first step should be implementing automatic discovery of devices. If all lights, fans, outlets, and transformers can be determined automatically, that limits the amount of data that needs to be collected from the user in a config flow.

**Comment by Expl0dingBanana** [comment]
ConfigFlow has been implemented for Auth as part of #86

**Comment by Expl0dingBanana** [comment]
I believe this has been resolved with 3.0. Please re-open the issue if the problem persists
