### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by nemisphere** [jdeath/Hubspace-Homeassistant#2]
Hello, I'm getting the following error in my logs, not sure what's going on, any help would be appreciated:

Logger: homeassistant.components.light
Source: custom_components/hubspace/hubspace.py:63
Integration: Light (documentation, issues)
First occurred: 7:52:58 PM (1 occurrences)
Last logged: 7:52:58 PM

Error while setting up hubspace platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hubspace/light.py", line 53, in setup_platform
    entities = [HubspaceLight(username, password, friendlyname) for friendlyname in config.get(CONF_FRIENDLYNAMES)]
  File "/config/custom_components/hubspace/light.py", line 53, in <listcomp>
    entities = [HubspaceLight(username, password, friendlyname) for friendlyname in config.get(CONF_FRIENDLYNAMES)]
  File "/config/custom_components/hubspace/light.py", line 77, in __init__
    self._refresh_token = hs.getRefreshCode(self._username,self._password)
  File "/config/custom_components/hubspace/hubspace.py", line 63, in getRefreshCode
    session_state = re.search('session_state=(.+?)&code', location).group(1)
  File "/usr/local/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object

Here's my configuration in my configuration.yaml:
light:
  - platform: hubspace
    username: <redacted>
    password: <redacted>
    friendlynames:
      - 'WindowStrip'

**Comment by jdeath** [comment]
Hmm, not sure. The log is not very descriptive. Has it ever worked for you? I have been messing with it to support RGBW, so might have broken something. Looks like the login is not working. Perhaps double check you are using the latest version and triple check your username and password. Your password is submitted right before the error you are hitting.
I just restarted my version, and it works, so my guess is wrong username or password.

**Comment by nemisphere** [comment]
So, my password contained some symbols which I think may have caused some issues with your code, symbols were ! * %.

I changed my password to have no symbols and now it's progressing further.

I'm now getting this error which may have been what you were mentioning above with your RGBW changes:
Logger: homeassistant.components.light
Source: custom_components/hubspace/light.py:137
Integration: Light (documentation, issues)
First occurred: 10:17:49 PM (1 occurrences)
Last logged: 10:17:49 PM

hubspace: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 737, in async_device_update
    await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hubspace/light.py", line 137, in update
    if self._useBrightness:
AttributeError: 'HubspaceLight' object has no attribute '_useBrightness'


Thanks for putting this together, much appreciated!

**Comment by jdeath** [comment]
Thanks. Fixed that bug. Try getting the latest release or update your light.py from the repo manually..

**Comment by nemisphere** [comment]
The new update resolves the error I was getting and I now see the light in HASS!

However, I can’t control the light, when I click the switch, it reverts back to it’s previous state.  I do see the lights state and when I turn it off manually I see the state change in HASS.

thanks again for your work on this!

**Comment by jdeath** [comment]
That is weird. Can you tell me the model of your light? Does it support dimming or RGB? It must need another value besides "power" to actually turn it off. Without mitm the app, I am not sure what other commands to send.

In this repo, there is a "TestHubspace,py" If you are able to edit that and run it, can you DM the output when light is on and off?  DM me the output on the homeassistant forum, as some info could be private. If that doesn't help, we can look at other options. You can also try replacing the hubspace.py and light.py with the version in the dev branch. that is the version I am using now, so may be easier to diagnose...
