### ISSUE TITLE
New device request: lock

### ISSUE THREAD

**Issue by jasonhurlbert** [jdeath/Hubspace-Homeassistant#25]
I have a Defiant branded deadbolt that uses the Hubspace API that I would like to try to get into this integration.

Here is the json output from the TestHubspace.py script: https://gist.github.com/jasonhurlbert/8a37e112e4d35aeb33e74b37e6bcfef5

I put the output in a gist because the output was nearly 2,000 lines long. 

Let me know how I can help, thanks!

**Comment by jdeath** [comment]
Thanks. I think I got it. Can you post another output of the TestHubspace.py with the lock "locked". I think it was unlocked when you did this? 
@dloveall I'll try to get this working, then maybe you can add the auto discovery

**Comment by jasonhurlbert** [comment]
Yes, you are correct, the first output was when the lock was in the unlocked position.

Here is another output, when in the locked position: https://gist.github.com/jasonhurlbert/635090c39137c339742575b6cd2d273e

**Comment by jdeath** [comment]
ok, download the latest light.py (make sure to download the raw file). Replace the one in custom_components/hubspace/ and restart. You must specify your friendlyname in the config. On is locked, off is unlocked (I can switch if you prefer)

Funny, the model number is specified as TBD. Hopefully this will work. Your battery level and the last event is stored as an attribute. It might take a couple of iterations to get this to work, since I cannot test myself

**Comment by jasonhurlbert** [comment]
Ok, I'm not sure what to make of this. I see the entity, but I can't toggle the state from Home Assistant. If I turn the deadbolt manually, the state changes in Home Assistant. I don't see anything in the HA logs.

**Comment by jdeath** [comment]
Not sure either. It must require sending another field to lock/unlock. At least you can see the status. :)
I might need your user/password and inspect the app traffic. However, not sure if my inspection setup still works. I'll reach out

**Comment by jdeath** [comment]
I added another field on a hunch, not sure if it will work. try the latest file.

**Comment by jasonhurlbert** [comment]
You've made forward progress for sure, as I can now sort of toggle the state from HA. I'm wondering if some sort of state/lock position has to be sent along as well though. When I toggle the lock from HA when it is in the unlocked position, it will lock, then immediately unlock. If I toggle the lock when it is in the locked position, it will unlock, lock, then unlock again.

**Comment by jdeath** [comment]
Is that lock-unlock behavior new from the last version I posted? If so, let's try two more things.

Try the latest version, where I just send the 'direction-check' command. If that doesn't work, I have one other idea to try.

**Comment by jasonhurlbert** [comment]
Yes, the lock-unlock behavior was new from the first version you posted. The first version wouldn't control the lock at all. The 2nd version you posted started controlling the lock, but introduced the lock-unlock behavior.

I just tried the latest version, and it has the same behavior as the last version (with the lock-unlock behavior). Thanks!

**Comment by jdeath** [comment]
Weird. I think I'd need your username/password to diagnose to find the correct set of commands.

**Comment by jdeath** [comment]
I tried one more thing. give it a try.

**Comment by jasonhurlbert** [comment]
Yes, the last change you made has fixed the strange lock-unlock behavior, and now behaves in an expected way, thank you!

One last thing, I've noticed it takes the state 30-60 seconds to update in HA. Is this because of some sort of rate limiting mitigation so the API doesn't rate limit the integration?

Thanks again for your help!

**Comment by jdeath** [comment]
Cool! Just needed to send locking/unlockding instead of locked/unlocked. I'll draft a release shortly.

Yes, this is an API limiter. The integration pings the hubspace servers every 30 seconds. It is possible to shorten it, but then they'd probably get mad. This leads to the lag you see.

**Comment by jasonhurlbert** [comment]
Awesome, I figured that's what was going on. Thanks again for getting this working!

**Comment by jdeath** [comment]
I picked up one of these locks. My plan is to write a homeassistant bluetooth integration so can have local control with no need for WiFi or the cloud. It is not installed yet (might take a couple weeks to get around to it). However, I have been able to get the deviceID over bluetooth. Cannot get farther because the lock in not installed and will not pass the direction test, but looks promising.

**Comment by jdeath** [comment]
Not much progress. It does works via WIFI with the integration, but not BT. I could figure out the field that shows the status and see when the lock state changes, but do not know how to decrypt the message. So not very useful!

To help, use a nRF BT dongle with WireShark to see if you can sniff the encryption key. It is beyond my skills
