### ISSUE TITLE
Lock takes a long time to respond, possible issues with entity identifying as a light.

### ISSUE THREAD

**Issue by grainsoflight** [jdeath/Hubspace-Homeassistant#27]
Wifi lock can currently take up to 30 seconds to respond (that is if connected, sometimes it becomes unresponsive.) Also, Im somewhat worried about the lock identifying as a light as it seems that it could become really easy to accidentally loop it's state in with other lights in the room when creating scenes/automations etc.

**Comment by jdeath** [comment]
Weird. Only so much I can do without having one. It should respond right away to a lock command, but can take 30 seconds to realize a state change since it polls the cloud every 30 seconds.

Feel free to edit the code to make a dedicated lock entity.

**Comment by grainsoflight** [comment]
Makes sense as to why theres a delay. Its not a huge deal as most of the time it eventually changes. I'm not super familiar with tweaking the code for entities in homeassistant but if I work it out Ill let you know. Id hate to turn some light off and accdentally open the back door XD
