### ISSUE TITLE
output from test

### ISSUE THREAD

**Issue by tedserreyn** [jdeath/Hubspace-Homeassistant#31]
I had to hardcode username/password in code.

eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2OThhMDY0NS0wZDljLTRlYTktODhiZS0xYzc1OGVjOGIxOGYifQ.eyJpYXQiOjE2NzM3MDcxNjUsImp0aSI6IjBjOTdlNjViLWFmYWYtNDY3Yi05NzU1LWY0YTI3NGEwMDI2MyIsImlzcyI6Imh0dHBzOi8vYWNjb3VudHMuaHVic3BhY2Vjb25uZWN0LmNvbS9hdXRoL3JlYWxtcy90aGQiLCJhdWQiOiJodHRwczovL2FjY291bnRzLmh1YnNwYWNlY29ubmVjdC5jb20vYXV0aC9yZWFsbXMvdGhkIiwic3ViIjoiZjowYjYyZDRlYS1mYmFlLTRmNTYtYjY4MS02Y2E5NmIzZDEwYTM6YTJlMTBmNDAtMWIxOS00ZjJjLWI0Y2ItYWRkOTY5YmZjYzRjIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6Imh1YnNwYWNlX2FuZHJvaWQiLCJzZXNzaW9uX3N0YXRlIjoiMjVhMzUyOGMtY2Y4Ny00NzIxLWFkODAtZTU3YzA0ODY5ZDZlIiwic2NvcGUiOiJvcGVuaWQgZW1haWwgb2ZmbGluZV9hY2Nlc3MgcHJvZmlsZSIsInNpZCI6IjI1YTM1MjhjLWNmODctNDcyMS1hZDgwLWU1N2MwNDg2OWQ2ZSJ9.bcVaDHBWtTETgOlkdMxLTA4HG8igl47T8bd5HWp-nIk
Light: Home ID 3265f0fb-d505-4659-bc77-23899c796510
Light: Office ID b4e972bd-6ca0-42bc-bdba-c2eb54c1e377
Light: Testofficelight ID d6fed631-b47c-442e-9648-a657452adb69
Traceback (most recent call last):
  File "/home/ted/testit.py", line 346, in <module>
    [child, deviceId,model] = getChildId(refresh_token,accountId,lightname)
  File "/home/ted/testit.py", line 167, in getChildId
    return child,deviceId,model
UnboundLocalError: local variable 'model' referenced before assignment

**Comment by jdeath** [comment]
Not sure why the test code is not working. What happens in homeassistant? Your friendlyname is : Testofficelight

Since it is a light, you probably do not even need to specify it just add to your configuration:

```
light:
  - platform: hubspace
    username: your_hubspace_username 
    password: your_hubspace_password
```

**Comment by tedserreyn** [comment]
Yeah tried that, I think it is a problem with setting up the login.  My username is an email, not sure if I need to quote it out ***@***.******@***.***> vs ***@***.******@***.***>”  like I did in the test code.

I tried pulling off the friendly names with no impact, same result.



From: jdeath ***@***.***>
Date: Saturday, January 14, 2023 at 12:47 PM
To: jdeath/Hubspace-Homeassistant ***@***.***>
Cc: Ted Serreyn ***@***.***>, Author ***@***.***>
Subject: Re: [jdeath/Hubspace-Homeassistant] output from test (Issue #31)

Not sure why the test code is not working. What happens in homeassistant? Your friendlyname is : Testofficelight

Since it is a light, you probably do not even need to specify it just add to your configuration:

light:

  - platform: hubspace

    username: your_hubspace_username

    password: your_hubspace_password

**Comment by jdeath** [comment]
No quotes needed. As a check,  make sure no special characters in your password or username.
