### ISSUE TITLE
Fans status not updating

### ISSUE THREAD

**Issue by kevinbegley** [jdeath/Hubspace-Homeassistant#33]
Hello,

Thank you for creating this integration. I seem to be having issues with the fan entity. The fan does not seem to report back to HA. If I turn on/off the fan or change the speed within the app it never reports back to HA. I am able to control the fan speed within HA but I cannot turn the fan on or off from HA. Please let me know what information you need from me.

Thank you,
Kevin

**Comment by jdeath** [comment]
I would first post on the Home Assistant forums as others can help you. I don't have fan. Did you try removing the friendlyname and let the integration find it automatically? It is entirely possible, Hubspace changed the AP or you have a new modeI. In that case, run the [TestHubspace.py](https://github.com/jdeath/Hubspace-Homeassistant/blob/main/TestHubspace.py) file and upload the information (it will be anonymized).

**Comment by kevinbegley** [comment]
Hello,

Attached is the results from the script. Please let me know if you need any additional information.

[TestHubspace Results.txt](https://github.com/jdeath/Hubspace-Homeassistant/files/11224208/TestHubspace.Results.txt)

Thanks,
Kevin

**Comment by jdeath** [comment]
Everything looks fine and the same as another person's fan data. Are you just using the light entity or did you make a fan template? If using the fan template, it is easy to mess things up so confirm you can control everything without the template.

**Comment by kevinbegley** [comment]
Hello,

I have attached a video file showing what happens.  I am not using the fan template. It will allow me to control the speed but as seen as I close the entity and reopen it shows it off when it is on. I also am unable to turn it off. It's like the power button does not work, and it ever send any data from the webservice back to HA. Please let me know if you have additional questions.


https://user-images.githubusercontent.com/24796488/232168514-70fd4922-b2db-481b-b731-667d0e3f9cc9.mp4


Thanks,
Kevin

**Comment by jdeath** [comment]
The fan is really a pain. Weird changing speed works, but not turning off.

First thing to try:
Are you specifying a friendlyname in the yaml? If so, try removing the freindlyname and see if it works better. If you are not specifying a friendlyname, add the freindlyname of the parent device and see if it works better. You probably have 2-3 names in the hubspace app for the fan. You want the one shown under "product name" I think.

thing to try second:
Around line 800 in light.py you should see the below text. It turns the fan off, then set the speed to zero. Perhaps comment out the statement setting the fan speed to zero. and see if that helps. 

```
 def turn_off(self, **kwargs: Any) -> None:
        """Instruct the light to turn off."""
        self._hs.setStateInstance(self._childId, "power", "fan-power", "off")
        self._hs.setStateInstance(
            self._childId, "fan-speed", "fan-speed", "fan-speed-000"
        )
        #self.update()
```

**Comment by kevinbegley** [comment]
Hello,

So to answer your first question I have the yaml set as the following, and I tried it without the friendlynames and it only shows the first light and no fan. I have two light/fans in the app. 

light:
  - platform: hubspace
    username: xxxx@xxx.com
    password: xxxx
    friendlynames:
      - 'cr'
      - 'sr'

As for the second question. I went ahead and commented out the following "line 621-625" and got the same response. It's like Hubspace is not sending data back to HA.

    def turn_off(self, **kwargs: Any) -> None:
        """Instruct the light to turn off."""
        self._hs.setStateInstance(self._childId,'power','fan-power','off')
#        self._hs.setStateInstance(self._childId,'fan-speed','fan-speed','fan-speed-000')
        self.update()

Please let me know if you need anything else or if there is anything else you want me to try. Thank you for helping out on this.

-Kevin

**Comment by jdeath** [comment]
I really don't know. You could try adding the debug lines in your config file and look through your log. Something is messed up.

```
logger:
  default: error
  logs:
    custom_components.hubspace: debug
```

and see if anything sticks out in the logs. You can also put 
```_LOGGER.debug("XXX" + variableName)``` in the turn_on() and turn_off() and update() functions in HubspaceFan to see if information is being returned. For instance, in update() add: 
```_LOGGER.debug("state: " + self._state)``` and see if it spits out on/off in the logs.

Look though the logs and see if it throws any errors.

**Comment by kevinbegley** [comment]
Hello,

I was able to resolve the issue. I found that I had a number of disable hubspace entity. Once I removed them all and them removed the friendlynames from the YAML, everything worked perfect. Thank you for all you help.

-Keivn
