### ISSUE TITLE
Ceiling Fan support

### ISSUE THREAD

**Issue by k2xl** [jdeath/Hubspace-Homeassistant#37]
Just picked up hubspace integrated ceiling fan from home depot. It seems to connect to the fan but how can I control the fan speed?

Unrelated - any lovelace card recommendations for ceiling fan :-)?

**Comment by jdeath** [comment]
Please review the readme. There is documentation on setting up a fan. If it doesn't work, run the TestHubspace script and post the results. Perhaps you have a new model that is not yet supported. I don't have a fan, so can't help on lovelace cards.
