### ISSUE TITLE
Hubspace light socket ereor

### ISSUE THREAD

**Issue by steveothesane** [jdeath/Hubspace-Homeassistant#41]
Logger: homeassistant.components.light
Source: custom_components/hubspace/light.py:140
Integration: Light (documentation, issues)
First occurred: 3:18:10 PM (1 occurrences)
Last logged: 3:18:10 PM

Error while setting up hubspace platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 320, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hubspace/light.py", line 140, in setup_platform
    _LOGGER.debug("Switch on Model " + model)
                  ~~~~~~~~~~~~~~~~~~~^~~~~~~
TypeError: can only concatenate str (not "NoneType") to str

**Comment by jdeath** [comment]
Please send the information described in the support new model section. Not sure a light socket has been implemented. The current version of the code *might* work if you correctly specify the freindlyname, but the automatic discovery feature probably will not.
