### ISSUE TITLE
Driskol with blank model having entity problems

### ISSUE THREAD

**Issue by Modusmundi** [jdeath/Hubspace-Homeassistant#42]
Hey there,

So I've been trying to figure out why my Driskol fan will turn on and off, but not change fan speeds.  I'm pretty sure I've isolated it at this point (By way of messing around with your TestHubspace.py script as well as poking around in the entity and trying to get around it).  I'm honestly unsure if there is another identifier in the data that comes back that could be used- as far as I can tell deviceID is unique.  I am curious if there is some different in settings between the fans (Like, attribute-level, not value-level as it's pretty apparent all of them have weird differences in fan speed which is super frustrating) that you could then use to derive which fan you're addressing.  I've been trying to work around it myself at the entity level and haven't had much luck- then again I'm kind of a novice to all of this.  Do you have any ideas?

If you want I can hand you the TestHubspace.py results, but I don't know if there's a good way to fix this.  I guess I could put them into homekit but frankly I want to avoid homekit if possible.

Also as a head's up I'm probably going to add an option to output the results of the tester to a file since that's a ton of output in the next few weeks.

**Comment by Modusmundi** [comment]
Okay so I thought a little bit while I was having dinner with my wife and I'd bet we could 100% fix the blank-model issue by ingesting an optional key that defines the model.  So for instance in the configuration we might have 

```
model: 11PR38120RGBWH1
```

The problem is given your code (I haven't dug into light.py yet) I'm unsure how to make that relate to a specific entity.  Given what I understand the friendlynames config to be, and roomnames config to be, they are simple lists which means I don't think there is an easy way to relate a given entity or room name to a model in a fixed manner.

I think I'm going to try to delete my current entities, throw in your latest light.py since it looks like there were some changes, and see if that remediates my issue as it looks like there's actually a creation case for the DriskolFan now when it has a blank model-
```

        if deviceClass == "fan" and model == "":
            model == "DriskolFan"
```
The problem of course is going to be if other fans come out with blank models and then default to DriskolFan.  Such a stupid API, not being consistent on data and changing things in it seemingly with every new fan.

**Comment by Modusmundi** [comment]
I found the problem, it was staring right at me.

I will send a PR shortly.

**Comment by jdeath** [comment]
Thanks for all this. I merged your PR. Yes, there is at least another fan that returns a empty model number. And of course, that model has a different number of speeds. I had him manually override the code. I need a better solution, but I don't have a fan so it is hard for me to experiment. Issue 38 has our discussion on it. https://github.com/jdeath/Hubspace-Homeassistant/issues/38

I was a novice before I made this integration too! Have to start somewhere.

**Comment by Modusmundi** [comment]
I took a look at the issue they were having.  Maybe we can poll
capabilities somehow during initial creation to assign a model name, and
that might fix it for now.  I don’t code in Python in my day job, and the
coding I do is more integration stuff than actual system engineering
stuff.  Lemme think about it, this might not be horrible to solve.

**Comment by Modusmundi** [comment]
Okay so I've got some time to think about this over the next few weeks, and what I think I need to really figure out what we can do to isolate for these new/different fans is to look at the values that each of their functionclasses have.

To that end, do you have examples of what the other fans that you have worked with so far to support have in terms of functionClass, functionInstance, and values?  E.G.:

```
  - functionClass: fan-reverse
    functionInstance: fan-reverse
    value: forward
    lastUpdateTime: XXXXXXXXXX
  - functionClass: power
    functionInstance: fan-power
    value: 'on'
    lastUpdateTime: XXXXXXXXXX
  - functionClass: toggle
    functionInstance: comfort-breeze
    (value: disabled)
```

**Comment by jdeath** [comment]
Thank you for the PR.
The example I have are posted: https://github.com/jdeath/Hubspace-Homeassistant/tree/main/sample_data
Perhaps there are others buried in old issues. There are a few fan examples there.
It would be better to probe the API for supported capability and set it all up automatically, but I have not had the time (and it is hard to test without the device). As an example, someone added code for color temperature, which processes the API json and finds valid temperature choices. Something like that could be done more universally. See here: https://github.com/jdeath/Hubspace-Homeassistant/blob/c23248a4d81d7ce7f714d3b4a4fcd5f53339affe/custom_components/hubspace/light.py#L387

I did make some changes to support another model of fan this week. Have not done a new release yet

**Comment by Modusmundi** [comment]
Awesome.  I will see what I can figure out with postman and squirreling
around.
