### ISSUE TITLE
New Product Support

### ISSUE THREAD

**Issue by dannygiacomuzzi** [jdeath/Hubspace-Homeassistant#47]
LED STRIP. please help :) Mostly turn on and off and return to previous color and brightness config

Last login: Tue Jul 11 22:56:03 on ttys000
dgiaco@Dannys-MacBook-Pro ~ % cd '/Users/dgiaco/Downloads/' && '/usr/local/bin/python3'  '/Users/dgiaco/Downloads/TestHubspace.py'  && echo Exit status: $? && exit 1
Hubspace Username: dannygiacomuzzi@me.com
Hubspace Password: 
UUIDs, times, locations, names, MACs, and SSIDs have been redacted or randomized below.
[
    {
        "children": [
            "505c7806-18ce-4cd0-82fa-7466f7f3071d",
            "f2945dce-27fb-4db7-9566-73d20496f4ab"
        ],
        "createdTimestampMs": 0,
        "friendlyName": "Friendly Name 2",
        "id": "ea9490fd-3181-40ab-af78-a7357f4fada7",
        "locale": "en_US",
        "typeId": "metadevice.home",
        "updatedTimestampMs": 0,
        "version": 1
    },
    {
        "children": [
            "f2945dce-27fb-4db7-9566-73d20496f4ab"
        ],
        "createdTimestampMs": 0,
        "friendlyDescription": "",
        "friendlyName": "Friendly Name 1",
        "id": "505c7806-18ce-4cd0-82fa-7466f7f3071d",
        "image": "wallpaper01.jpg",
        "locale": "en_US",
        "tag": "",
        "typeId": "metadevice.room",
        "updatedTimestampMs": 0,
        "version": 1
    },
    {
        "children": [],
        "createdTimestampMs": 0,
        "description": {
            "createdTimestampMs": 0,
            "defaultImage": "linear-light-icon",
            "descriptions": [],
            "device": {
                "defaultName": "Linear Light",
                "deviceClass": "light",
                "manufacturerName": "EcoSmart",
                "model": "AL-TP-RGBCW-60-2116, AL-TP-RGBCW-60-2232",
                "profileId": "c6ada73c-d115-46c2-aef4-58fa80cc2fe8",
                "type": "device"
            },
            "functions": [
                {
                    "createdTimestampMs": 0,
                    "functionClass": "color-temperature",
                    "id": "3bd9029e-17bc-4cdb-8d1e-166cdbcc5717",
                    "schedulable": true,
                    "type": "numeric",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "b69cb1f6-7f3a-4313-acca-619484fecda7",
                                    "key": "3",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0
                                }
                            ],
                            "id": "b3447b58-94f5-4ff3-8ffa-c6b2d3e48bc1",
                            "name": "color-temperature",
                            "range": {
                                "max": 6500,
                                "min": 2200,
                                "step": 100
                            },
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "brightness",
                    "functionInstance": "color",
                    "id": "2fcec69b-b8ca-4b61-a90a-52ff12d018e8",
                    "schedulable": true,
                    "type": "numeric",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "ce6f8dfd-877b-4270-b958-aa7a8ee8c159",
                                    "key": "10",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0
                                }
                            ],
                            "id": "7f634208-1910-498b-8c03-c32a3ce162b8",
                            "name": "brightness",
                            "range": {
                                "max": 100,
                                "min": 1,
                                "step": 1
                            },
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "color-sequence",
                    "functionInstance": "preset",
                    "id": "ccfba635-a819-420c-9fbb-80f6b6631114",
                    "schedulable": true,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "b4ef7828-783b-465f-810b-7eafef83d6c6",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "301"
                                }
                            ],
                            "id": "59f8cf5e-3f4b-47e6-85f5-512a768df2c6",
                            "name": "flash",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "e59dcbbb-6247-460c-8eec-ae29bf5fa303",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "305"
                                }
                            ],
                            "id": "8b292f42-9e28-46da-80dd-9095e6bc630c",
                            "name": "jump-3",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "67159d14-64cb-4873-be35-448c138d0735",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "303"
                                }
                            ],
                            "id": "a4acc1a1-116a-4aed-ba36-8cc3e7f22084",
                            "name": "fade-3",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "7de3365b-967f-47bc-bf9a-edf35a2a2376",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "302"
                                }
                            ],
                            "id": "bfbe5cbc-8d93-4a5a-8c23-b3fbdc5e8e0a",
                            "name": "fade-7",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "1b0cf827-a823-4e2e-b4a7-eaf3d92ddb35",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "300"
                                }
                            ],
                            "id": "0e39e175-6b94-4773-9798-1947cd0e559f",
                            "name": "custom",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "6f2ef307-250f-49c3-ac22-966ef736e5f9",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "304"
                                }
                            ],
                            "id": "8549e0ed-f160-49ad-adcd-e47660c4e39b",
                            "name": "jump-7",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "color-rgb",
                    "id": "3c09a50e-2cf5-41dc-b862-78d8af42d7b5",
                    "schedulable": true,
                    "type": "object",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "format": "color-rgb",
                                    "id": "eaedafac-e765-4526-b092-152563d4d61a",
                                    "key": "4",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0
                                }
                            ],
                            "id": "636e367c-75e3-4cb9-9a4b-b53077190bc4",
                            "name": "color-rgb",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "restore-values",
                    "id": "ce6f3a22-9d70-405f-b7ad-2c715180c4b2",
                    "schedulable": false,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "e932906d-2254-4ea4-8e72-fc8ecff25fb9",
                                    "key": "100",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "2"
                                }
                            ],
                            "id": "739d3f35-93fb-48d1-9fe8-959f59cf92f5",
                            "name": "partial-restore",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "c0a26455-cadf-41db-9372-a2be55bb15d6",
                                    "key": "100",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "1"
                                }
                            ],
                            "id": "583c8a52-b1d3-465f-8142-dbafe874bfe0",
                            "name": "restored",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "1b699adb-cb04-45b3-8f56-4db8778e3122",
                                    "key": "100",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0"
                                }
                            ],
                            "id": "529268f6-e359-4bb6-a8eb-3d3c605703af",
                            "name": "not-restored",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "color-mode",
                    "id": "f5441919-204b-446f-a6fb-e2718d76ffd7",
                    "schedulable": true,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "388f91c5-a15b-4611-840a-7b88e6abd66f",
                                    "key": "5",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "1"
                                }
                            ],
                            "id": "4d48d53b-d041-4875-8564-cc127359aaf3",
                            "name": "color",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "7aba56dc-b493-4bfd-9ec0-688c015cdad0",
                                    "key": "5",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "3"
                                }
                            ],
                            "id": "f2f4baab-4242-4079-b17c-fd5bde26cb74",
                            "name": "mixed",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "fdaa7488-4123-41ae-bc41-42709641fcf1",
                                    "key": "5",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "2"
                                }
                            ],
                            "id": "a004fc1a-ed3c-4ed7-af51-d3233ddc8a02",
                            "name": "sequence",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "280e84ad-bf2c-4480-8330-bd8f949dce34",
                                    "key": "5",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0"
                                }
                            ],
                            "id": "f631be68-a462-4bf4-89c3-a5aefc95ecce",
                            "name": "white",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "toggle",
                    "functionInstance": "white",
                    "id": "02ccbe06-a629-42d9-8721-32b6b542b70e",
                    "schedulable": true,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "daff6dd6-3532-48bb-ae62-7df0bba553da",
                                    "key": "7",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "1"
                                }
                            ],
                            "id": "8f2a8c1d-f2c4-491b-81b5-1b882c3a3267",
                            "name": "on",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "0dff6268-35b8-4ec8-a45f-f270de1430fe",
                                    "key": "7",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0"
                                }
                            ],
                            "id": "6c36f686-032c-4889-822a-5c3dc730bbc4",
                            "name": "off",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "power",
                    "functionInstance": "primary",
                    "id": "5cc01b37-d33f-4569-9c90-18ec95b053f0",
                    "schedulable": true,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "00f5aab4-3720-4dac-a026-1beaad4d92aa",
                                    "key": "1",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0"
                                }
                            ],
                            "id": "e5037a95-5f39-412a-b449-251f5ab39d6d",
                            "name": "off",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "0433e2aa-4d13-4a11-964c-45ad22065a2f",
                                    "key": "1",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "1"
                                }
                            ],
                            "id": "c3b697ce-7a21-4661-a068-537c5f74855c",
                            "name": "on",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "toggle",
                    "functionInstance": "color",
                    "id": "4cac775f-fe3f-41ed-869c-f19aee0f92b5",
                    "schedulable": true,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "f6884acb-8fed-4501-b3c1-095b9cb6c449",
                                    "key": "8",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "1"
                                }
                            ],
                            "id": "312827ed-c5a3-482f-9105-e7c44d83a4e5",
                            "name": "on",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "e03435a5-0ea0-42af-8c99-05c163863d55",
                                    "key": "8",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0"
                                }
                            ],
                            "id": "064b950e-6fab-42e8-8756-8a1f76642396",
                            "name": "off",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "brightness",
                    "functionInstance": "primary",
                    "id": "45eab4ab-de4b-49ae-aec5-8929898d2f72",
                    "schedulable": true,
                    "type": "numeric",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "8d9433ee-2cd4-4fff-94a3-be1c5479197c",
                                    "key": "2",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0
                                }
                            ],
                            "id": "daa8792a-b571-489f-9e42-b567ad05bed1",
                            "name": "brightness",
                            "range": {
                                "max": 100,
                                "min": 1,
                                "step": 1
                            },
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "color-sequence",
                    "functionInstance": "custom",
                    "id": "493a540a-14ae-45e6-a5b8-1ac4b21fd2b4",
                    "schedulable": true,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "574c9e2e-3182-4dd7-9363-7a159b8497fb",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "010700FF000064140000FF006414000000FF641400"
                                }
                            ],
                            "id": "9eccdc4d-f954-4df4-b212-b5206951fd59",
                            "name": "rainbow",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "89dfbe85-c446-4c35-be80-dc05fe2e832e",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0B0000CC105B000000"
                                }
                            ],
                            "id": "8b3ed672-94fa-459c-b14e-7a0362423fc1",
                            "name": "getting-ready",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "0c866837-0e6d-4d96-9edf-f60aef891ef9",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0504008C0A280008078C0A05000000"
                                }
                            ],
                            "id": "cc8b71c1-de2c-4564-abe9-3037ad69aaa3",
                            "name": "sleep",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "17156ee9-cbb7-497f-9359-8cd54e3e216c",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "044B00FF0000641400FFFFFF6414000000FF641400"
                                }
                            ],
                            "id": "e6cc16dd-35fd-481d-b132-a679006ce73a",
                            "name": "july-4th",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "ff35422c-63de-4e3e-9c1c-42710a428af1",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "034700FF0000640A0000FF00640A00"
                                }
                            ],
                            "id": "0b9db3a6-d74e-4a2f-81ae-fff09fc54d0a",
                            "name": "christmas",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "018e161b-d03c-4ca9-bf67-64bcc57171bd",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0D4700C61C1C640A00FF0000640A00"
                                }
                            ],
                            "id": "a2dceff4-8b1e-4190-9aad-16fd3a78fb6a",
                            "name": "valentines-day",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "6cff0a41-a4e8-4d52-b5c5-e154e2ba7e86",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0C000088130A000000"
                                }
                            ],
                            "id": "9399cfd0-26e2-44c2-8787-4ef90edb47d6",
                            "name": "moonlight",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "7302e027-6aa3-4be3-a443-9c8577b81948",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0204008C0A050008078C0A64000000"
                                }
                            ],
                            "id": "3ef62fdc-3b3f-4e6c-ad57-05a1d181d400",
                            "name": "wake-up",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "349cba74-961e-42d7-aaf6-b3921444ec51",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0A00008C0A05000000"
                                }
                            ],
                            "id": "1a45312e-f382-420f-b045-614802f8b5c5",
                            "name": "nightlight",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "4eb97521-e79c-4069-8f70-60fe86f492cd",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "070000800C28000000"
                                }
                            ],
                            "id": "741be153-195b-4a8c-afdc-5d70806e62ca",
                            "name": "chill",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "74994ab1-2037-4343-9883-006f5c1e33fc",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "60000318115200000"
                                }
                            ],
                            "id": "ac10f312-5e63-423a-af41-bd7ef7b7273a",
                            "name": "focus",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "12bf44fc-9ee0-4172-b590-d98c049f9a93",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "90000911106500000"
                                }
                            ],
                            "id": "5a9a8b58-2da8-46b7-8229-18baffa1aa6b",
                            "name": "clarity",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "eb26fd7c-20b1-4fc5-8a49-2535a81b70d3",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "080000F00A3E000000"
                                }
                            ],
                            "id": "9c44b5ba-0d68-40f3-bac9-e084475c6991",
                            "name": "dinner-party",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "brightness",
                    "functionInstance": "white",
                    "id": "bfd03324-9fd0-4ca3-8817-5db403648ee9",
                    "schedulable": true,
                    "type": "numeric",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "2f04ee3d-d951-4e43-8812-5fca30b4a866",
                                    "key": "9",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0
                                }
                            ],
                            "id": "db11aa16-5b92-4b9f-b400-696fb51683d7",
                            "name": "brightness",
                            "range": {
                                "max": 100,
                                "min": 1,
                                "step": 1
                            },
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "speed",
                    "functionInstance": "color-sequence",
                    "id": "ed4a2075-fde8-4eed-a043-5946730ee921",
                    "schedulable": true,
                    "type": "numeric",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "900df181-cf87-41d9-a86c-10e15b387ced",
                                    "key": "11",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0
                                }
                            ],
                            "id": "974ca657-9e1e-4774-a958-23c8738e288b",
                            "name": "speed",
                            "range": {
                                "max": 10,
                                "min": -10,
                                "step": 1
                            },
                            "updatedTimestampMs": 0
                        }
                    ]
                }
            ],
            "id": "83fc8934-0161-4054-9ff2-7a60ff3603be",
            "updatedTimestampMs": 0,
            "version": 1
        },
        "deviceId": "8d5852449364aba0",
        "friendlyDescription": "",
        "friendlyName": "Friendly Name 0",
        "id": "f2945dce-27fb-4db7-9566-73d20496f4ab",
        "image": "",
        "locale": "es_US",
        "state": {
            "metadeviceId": "f2945dce-27fb-4db7-9566-73d20496f4ab",
            "values": [
                {
                    "functionClass": "color-temperature",
                    "lastUpdateTime": 1688891293129,
                    "value": 2200
                },
                {
                    "functionClass": "brightness",
                    "functionInstance": "color",
                    "lastUpdateTime": 1688895008172,
                    "value": 1
                },
                {
                    "functionClass": "color-sequence",
                    "functionInstance": "preset",
                    "lastUpdateTime": 1688892335426,
                    "value": "custom"
                },
                {
                    "functionClass": "color-rgb",
                    "lastUpdateTime": 1688891741037,
                    "value": {
                        "color-rgb": {
                            "b": 255,
                            "g": 0,
                            "r": 255
                        }
                    }
                },
                {
                    "functionClass": "restore-values",
                    "lastUpdateTime": 1688895130485,
                    "value": "restored"
                },
                {
                    "functionClass": "color-mode",
                    "lastUpdateTime": 1688891881468,
                    "value": "sequence"
                },
                {
                    "functionClass": "toggle",
                    "functionInstance": "white",
                    "lastUpdateTime": 1688893086885,
                    "value": "off"
                },
                {
                    "functionClass": "power",
                    "functionInstance": "primary",
                    "lastUpdateTime": 1688889842835,
                    "value": "off"
                },
                {
                    "functionClass": "toggle",
                    "functionInstance": "color",
                    "lastUpdateTime": 1688893670402,
                    "value": "off"
                },
                {
                    "functionClass": "brightness",
                    "functionInstance": "primary",
                    "lastUpdateTime": 1688890301160,
                    "value": 0
                },
                {
                    "functionClass": "color-sequence",
                    "functionInstance": "custom",
                    "lastUpdateTime": 1688895132056,
                    "value": "nightlight"
                },
                {
                    "functionClass": "brightness",
                    "functionInstance": "white",
                    "lastUpdateTime": 1688894529670,
                    "value": 1
                },
                {
                    "functionClass": "speed",
                    "functionInstance": "color-sequence",
                    "lastUpdateTime": 1688895056901,
                    "value": 0
                },
                {
                    "functionClass": "wifi-ssid",
                    "lastUpdateTime": 1688896690549,
                    "value": "SSID0"
                },
                {
                    "functionClass": "wifi-rssi",
                    "lastUpdateTime": 1688897673689,
                    "value": -56
                },
                {
                    "functionClass": "wifi-steady-state",
                    "lastUpdateTime": 1688888607738,
                    "value": "connected"
                },
                {
                    "functionClass": "wifi-setup-state",
                    "lastUpdateTime": 1688889465193,
                    "value": "connected"
                },
                {
                    "functionClass": "wifi-mac-address",
                    "lastUpdateTime": 0,
                    "value": "6825c6869ea5"
                },
                {
                    "functionClass": "geo-coordinates",
                    "functionInstance": "system-device-location",
                    "lastUpdateTime": 1688898188449,
                    "value": {
                        "geo-coordinates": {
                            "latitude": "0.024271023427644645",
                            "longitude": "0.7556523966511741"
                        }
                    }
                },
                {
                    "functionClass": "scheduler-flags",
                    "lastUpdateTime": 1688895697156,
                    "value": 1
                },
                {
                    "functionClass": "available",
                    "lastUpdateTime": 1688906859344,
                    "value": false
                },
                {
                    "functionClass": "visible",
                    "lastUpdateTime": 1688906859344,
                    "value": false
                },
                {
                    "functionClass": "direct",
                    "lastUpdateTime": 1688906859344,
                    "value": false
                },
                {
                    "functionClass": "ble-mac-address",
                    "lastUpdateTime": 0,
                    "value": "52449364aba0"
                }
            ]
        },
        "tag": "",
        "typeId": "metadevice.device",
        "updatedTimestampMs": 0,
        "version": 1
    }
]
Exit status: 0

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by jdeath** [comment]
Thanks for the test output. What exactly is not working? It should have on/off, brightness and RGB support. I never added color temp support, but I have not received other reports of this model not working.

After changing a setting, it can take 30s-60s for homeassistant to show the change.

**Comment by dannygiacomuzzi** [comment]
It is only a switch. On and Off. There isn’t a dimmer style UI like other lightbulbs i have that dim and change color. Also it frequently doesn't work. Not mathching the status of the switch on the home appOn Jul 12, 2023, at 7:29 AM, jdeath ***@***.***> wrote:﻿
Thanks for the test output. What exactly is not working? It should have on/off, brightness and RGB support. I never added color temp support, but I have not received other reports of this model not working.
After changing a setting, it can take 30s-60s for homeassistant to show the change.

**Comment by jdeath** [comment]
Try manually downloading latest light.py in the repo and restart home assistant. Maybe it will handle dimmer better. Not sure how to help not matching the app. It does the best it can.

**Comment by jdeath** [comment]
closing as stale
