### ISSUE TITLE
Request: Support for CD44bRGBW11W

### ISSUE THREAD

**Issue by Adanufgail** [jdeath/Hubspace-Homeassistant#50]
Hello, we recently purchased a bunch of these flush-mount ceiling lights. At present we set one up for testing, and I can do on/off with the default config, but cannot adjust RGB/color temp. I'm hopeful that it's pretty similar to other RGB lights and is a quick update.

Hubspace Username: UUIDs, times, locations, names, MACs, and SSIDs have been redacted or randomized below.
[
    {
        "children": [
            "7da09f07-7faf-4b1d-8705-2fbaf214783d",
            "4479ea23-a1b3-4f4a-b89b-d0d1d3ad875d"
        ],
        "createdTimestampMs": 0,
        "friendlyName": "Friendly Name 2",
        "id": "bed2c2be-b83a-454f-a7e7-d2a00b1935d7",
        "locale": "en_US",
        "typeId": "metadevice.home",
        "updatedTimestampMs": 0,
        "version": 1
    },
    {
        "children": [
            "4479ea23-a1b3-4f4a-b89b-d0d1d3ad875d"
        ],
        "createdTimestampMs": 0,
        "friendlyDescription": "",
        "friendlyName": "Friendly Name 1",
        "id": "7da09f07-7faf-4b1d-8705-2fbaf214783d",
        "image": "wallpaper05.jpg",
        "locale": "en_US",
        "tag": "",
        "typeId": "metadevice.room",
        "updatedTimestampMs": 0,
        "version": 1
    },
    {
        "children": [],
        "createdTimestampMs": 0,
        "description": {
            "createdTimestampMs": 0,
            "defaultImage": "round-puff-11-light-icon",
            "descriptions": [],
            "device": {
                "defaultName": "Flush Mount",
                "deviceClass": "light",
                "manufacturerName": "Commercial Electric",
                "model": "CD44bRGBW11W",
                "profileId": "d17eabcf-5df3-4444-9154-827c2bb9cdd4",
                "type": "device"
            },
            "functions": [
                {
                    "createdTimestampMs": 0,
                    "functionClass": "color-sequence",
                    "functionInstance": "preset",
                    "id": "f7b7d0d2-504c-4d14-9ed4-df93324c33e2",
                    "schedulable": true,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "3512b1db-7b35-4ef3-b2c9-e1be801d3e90",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "301"
                                }
                            ],
                            "id": "4928bf91-690b-47d4-b6e7-634211100306",
                            "name": "flash",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "e040ff9e-1599-42cf-bdc1-9c8af752f7eb",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "304"
                                }
                            ],
                            "id": "c128b6da-bf58-496d-a2e8-f6c53be5af6a",
                            "name": "jump-7",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "d9811759-7086-43da-a0f6-ba2cc85040bd",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "300"
                                }
                            ],
                            "id": "b5e2592c-2277-4173-b101-53bc9c8988c4",
                            "name": "custom",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "1d4233a6-e01a-49c5-8415-d264c25c41ce",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "305"
                                }
                            ],
                            "id": "bc55f942-9430-4d97-aad0-8ab9ab18b3df",
                            "name": "jump-3",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "2722bbbf-6fb7-4977-b499-2eb3247d165a",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "302"
                                }
                            ],
                            "id": "95ccb8eb-5353-4b07-afa0-3f41082394b7",
                            "name": "fade-7",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "0e3c8a6c-0716-4088-9b1c-0ad43919db85",
                                    "key": "6",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "303"
                                }
                            ],
                            "id": "7896fbc5-3463-40a1-b4c4-cfaa003776ae",
                            "name": "fade-3",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "power",
                    "id": "fa70e33e-a7ab-4cd8-8c21-639b61941b18",
                    "schedulable": true,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "2e2d9f3c-e526-462c-a1c4-eae35d6dd0e2",
                                    "key": "1",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "1"
                                }
                            ],
                            "id": "ed1eff32-ad03-4cc1-b771-c08356423c3d",
                            "name": "on",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "6de364c2-05de-47a8-a387-c33552863ca2",
                                    "key": "1",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0"
                                }
                            ],
                            "id": "245451df-c528-45f7-936f-c77f0231c961",
                            "name": "off",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "color-temperature",
                    "id": "30398622-d597-4a2e-bf75-858e5eae4d7a",
                    "schedulable": true,
                    "type": "numeric",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "fc76f38d-a71b-4896-9986-039ca47b5b49",
                                    "key": "3",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0
                                }
                            ],
                            "id": "28086671-135b-4e9e-968c-57f56f84ee07",
                            "name": "color-temperature",
                            "range": {
                                "max": 6500,
                                "min": 2700,
                                "step": 100
                            },
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "brightness",
                    "id": "c6692bc2-62ec-49bd-9cc5-3b866166efea",
                    "schedulable": true,
                    "type": "numeric",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "c314d6f7-9c9f-4fd7-8712-b40bdf28e6c2",
                                    "key": "2",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0
                                }
                            ],
                            "id": "f495d10b-673d-42ad-923a-451ce478d647",
                            "name": "brightness",
                            "range": {
                                "max": 100,
                                "min": 1,
                                "step": 1
                            },
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "restore-values",
                    "id": "51df8343-3749-4bef-afe4-dae551e226a6",
                    "schedulable": false,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "9ba1d70f-99eb-497a-ba33-bb1b2b068920",
                                    "key": "100",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "2"
                                }
                            ],
                            "id": "de565a7b-30a0-4942-bd22-0d85b1d4a3e9",
                            "name": "partial-restore",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "55fc6ab8-eb7d-41ed-8819-ce0c4cd78c5f",
                                    "key": "100",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0"
                                }
                            ],
                            "id": "b9176583-1699-470e-b048-714804d5955f",
                            "name": "not-restored",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "7c9f2771-47ff-4189-b127-d5685c3ac48d",
                                    "key": "100",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "1"
                                }
                            ],
                            "id": "d45a3ca8-7727-4a0c-a308-091c1ce70156",
                            "name": "restored",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "color-sequence",
                    "functionInstance": "custom",
                    "id": "7f573819-7b02-47e2-9fad-b411f7526f10",
                    "schedulable": true,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "fce4b08f-46f4-4c43-9a48-dcbb43690aa4",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "044B00FF0000641400FFFFFF6414000000FF641400"
                                }
                            ],
                            "id": "65c99033-4d5f-4654-96f8-2d415194af8d",
                            "name": "july-4th",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "e8f6915c-ae11-4c9f-ae4e-483987f7cfb7",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "034700FF0000640A0000FF00640A00"
                                }
                            ],
                            "id": "459d9b5e-15ff-4e7c-9818-9fa24cce96a8",
                            "name": "christmas",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "46db3e58-f52c-4b3c-a309-70cda9a2f15a",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "080000F00A3E000000"
                                }
                            ],
                            "id": "4590439e-026e-4164-b6e0-8a55d60b29eb",
                            "name": "dinner-party",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "cb5a9123-499c-4b1c-a2e6-96364d5b47dc",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0C000088130A000000"
                                }
                            ],
                            "id": "5020d303-b97d-4aa8-ade2-542b4d136d5b",
                            "name": "moonlight",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "a53f74c8-d7b9-4756-b86a-4612630fad35",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "60000371904700000"
                                }
                            ],
                            "id": "517ec8ac-f820-4be7-ae6c-077b8f80fd49",
                            "name": "focus",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "5e4c4bca-34d3-400c-88dc-bd44e26e8431",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "070000800C28000000"
                                }
                            ],
                            "id": "80e37205-2da4-46c4-a82a-fa7be85326e1",
                            "name": "chill",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "63ce1601-954f-46df-99ff-f332b24eff87",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "010700FF000064140000FF006414000000FF641400"
                                }
                            ],
                            "id": "29dd31f6-059e-444f-8a85-8f81c5c3fb5a",
                            "name": "rainbow",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "36d04381-ce84-477c-a80a-29d2b67a5bae",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0D4700C61C1C640A00FF0000640A00"
                                }
                            ],
                            "id": "6f179e53-ff5e-49ca-b9c0-0782560b7dbc",
                            "name": "valentines-day",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "dfc7d218-521e-4a7b-9217-b9002b455a33",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0504008C0A280008078C0A05000000"
                                }
                            ],
                            "id": "801b65ea-cc9e-4500-85e6-102666a77d80",
                            "name": "sleep",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "f195feb8-8e14-4396-9b2c-6d9753db5174",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0B0000CC105B000000"
                                }
                            ],
                            "id": "1bcc002f-2f95-4f7e-9205-95bf44163bc6",
                            "name": "getting-ready",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "3524ab80-35c0-49f1-87c8-fce22663c2d0",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0204008C0A050008078C0A64000000"
                                }
                            ],
                            "id": "fa8024ee-204a-4a8f-9c4d-5fc80f32ae76",
                            "name": "wake-up",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "89e97352-e78d-43af-a1f4-3ee926eae852",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "90001049043700000"
                                }
                            ],
                            "id": "29ec0be2-9b47-47af-b89d-6574abe21b73",
                            "name": "clarity",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "b86b567e-d669-4dc5-80d6-ba4441daa59b",
                                    "key": "300",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0A00008C0A05000000"
                                }
                            ],
                            "id": "3821b18f-9cd3-4b0f-b037-091f71faf3e5",
                            "name": "nightlight",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "speed",
                    "functionInstance": "color-sequence",
                    "id": "4c72341d-4edb-4b6e-a5da-d0abbd8857be",
                    "schedulable": true,
                    "type": "numeric",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "ed6dea12-1dac-4baa-bf08-6c24241b876c",
                                    "key": "11",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0
                                }
                            ],
                            "id": "1915a5dd-5477-4124-b3fc-c52a74ec26a3",
                            "name": "speed",
                            "range": {
                                "max": 10,
                                "min": -10,
                                "step": 1
                            },
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "color-mode",
                    "id": "971ea02c-67d3-4e83-83a3-c74dbf8dcc8f",
                    "schedulable": true,
                    "type": "category",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "2b5e2a28-7ce9-43ed-808c-ea8daf0f57c2",
                                    "key": "5",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "1"
                                }
                            ],
                            "id": "7e2470d7-d3ce-4ae1-84ed-9b39e9451381",
                            "name": "color",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "eb786f25-7f98-4129-a19c-ef761169d909",
                                    "key": "5",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "0"
                                }
                            ],
                            "id": "61c20c1b-c8e5-41cc-94df-072c145b5257",
                            "name": "white",
                            "range": {},
                            "updatedTimestampMs": 0
                        },
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "id": "8d9b3168-f29c-4e67-ac69-49e0a86c878f",
                                    "key": "5",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0,
                                    "value": "2"
                                }
                            ],
                            "id": "20948fe6-f96e-4f29-b7e6-9a1d51564d20",
                            "name": "sequence",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                },
                {
                    "createdTimestampMs": 0,
                    "functionClass": "color-rgb",
                    "id": "3d4ed092-8a69-484e-bc79-6e6990bff41f",
                    "schedulable": true,
                    "type": "object",
                    "updatedTimestampMs": 0,
                    "values": [
                        {
                            "createdTimestampMs": 0,
                            "deviceValues": [
                                {
                                    "createdTimestampMs": 0,
                                    "format": "color-rgb",
                                    "id": "1ed0ce46-25f6-41a8-8d83-40b3ffa7a37a",
                                    "key": "4",
                                    "type": "attribute",
                                    "updatedTimestampMs": 0
                                }
                            ],
                            "id": "e87b5d79-0e2b-49f6-8fe2-f3d5e7aaacb1",
                            "name": "color-rgb",
                            "range": {},
                            "updatedTimestampMs": 0
                        }
                    ]
                }
            ],
            "id": "bcc237a4-56c1-4238-b0c6-70bd5f9d0d62",
            "updatedTimestampMs": 0,
            "version": 1
        },
        "deviceId": "872fb7c530765e43",
        "friendlyDescription": "",
        "friendlyName": "Friendly Name 0",
        "id": "4479ea23-a1b3-4f4a-b89b-d0d1d3ad875d",
        "image": "",
        "locale": "en_US",
        "state": {
            "metadeviceId": "4479ea23-a1b3-4f4a-b89b-d0d1d3ad875d",
            "values": [
                {
                    "functionClass": "color-sequence",
                    "functionInstance": "preset",
                    "lastUpdateTime": 1691298296360,
                    "value": "custom"
                },
                {
                    "functionClass": "power",
                    "lastUpdateTime": 1691295806151,
                    "value": "on"
                },
                {
                    "functionClass": "color-temperature",
                    "lastUpdateTime": 1691295854031,
                    "value": 3000
                },
                {
                    "functionClass": "brightness",
                    "lastUpdateTime": 1691299252562,
                    "value": 100
                },
                {
                    "functionClass": "restore-values",
                    "lastUpdateTime": 1691297840762,
                    "value": "partial-restore"
                },
                {
                    "functionClass": "color-sequence",
                    "functionInstance": "custom",
                    "lastUpdateTime": 1691299202021,
                    "value": "chill"
                },
                {
                    "functionClass": "speed",
                    "functionInstance": "color-sequence",
                    "lastUpdateTime": 1691297542023,
                    "value": 1
                },
                {
                    "functionClass": "color-mode",
                    "lastUpdateTime": 1691300131115,
                    "value": "color"
                },
                {
                    "functionClass": "color-rgb",
                    "lastUpdateTime": 1691296719295,
                    "value": {
                        "color-rgb": {
                            "b": 255,
                            "g": 0,
                            "r": 136
                        }
                    }
                },
                {
                    "functionClass": "wifi-ssid",
                    "lastUpdateTime": 1691294781803,
                    "value": "SSID0"
                },
                {
                    "functionClass": "wifi-rssi",
                    "lastUpdateTime": 1691295035934,
                    "value": -47
                },
                {
                    "functionClass": "wifi-steady-state",
                    "lastUpdateTime": 1691293992875,
                    "value": "connected"
                },
                {
                    "functionClass": "wifi-setup-state",
                    "lastUpdateTime": 1691294204403,
                    "value": "connected"
                },
                {
                    "functionClass": "wifi-mac-address",
                    "lastUpdateTime": 0,
                    "value": " 394d6cddc13"
                },
                {
                    "functionClass": "geo-coordinates",
                    "functionInstance": "system-device-location",
                    "lastUpdateTime": 1691295143324,
                    "value": {
                        "geo-coordinates": {
                            "latitude": "0.42729039033431604",
                            "longitude": "0.7492963343074842"
                        }
                    }
                },
                {
                    "functionClass": "scheduler-flags",
                    "lastUpdateTime": 1691294588458,
                    "value": 0
                },
                {
                    "functionClass": "available",
                    "lastUpdateTime": 1691300481357,
                    "value": true
                },
                {
                    "functionClass": "visible",
                    "lastUpdateTime": 1691300481357,
                    "value": true
                },
                {
                    "functionClass": "direct",
                    "lastUpdateTime": 1691300481357,
                    "value": true
                },
                {
                    "functionClass": "ble-mac-address",
                    "lastUpdateTime": 0,
                    "value": "b7c530765e43"
                }
            ]
        },
        "tag": "",
        "typeId": "metadevice.device",
        "updatedTimestampMs": 0,
        "version": 1
    }
]

**Comment by jdeath** [comment]
Try replacing your light.py in custom_componts/hubspace/ with this
https://github.com/jdeath/Hubspace-Homeassistant/blob/main/custom_components/hubspace/light.py
let me know if it works.

**Comment by Adanufgail** [comment]
That works! I do notice it takes a good 3-7 seconds for updates to push, but I think this is a limitation due to how you're doing the push, and doesn't affect our usage since we are mainly looking to do time-based dimming so a few seconds of delay are fine.

**Comment by jdeath** [comment]
Glad it worked. Yes, everything takes a couple seconds and takes ~30 to register any changes. Wish I knew a better way. I'm make a release shortly.
