### ISSUE TITLE
hubspace doorbell

### ISSUE THREAD

**Issue by aurochsen** [jdeath/Hubspace-Homeassistant#57]
I found the hubspace doorbell and wonder if its possible to detect the state in home assistant when the doorbell is pushed to trigger a notification? Here is a output from the api which is long as its lists the different chimes over and over again. 
[apioutput.json](https://github.com/jdeath/Hubspace-Homeassistant/files/13061081/apioutput.json)

**Comment by jdeath** [comment]
Looks like API returns the ringing state. You probably need to hit the API reasonably often to catch it. But looks possible. I do not see a corresponding ringing. Usually the API dump shows all possible values. Can you make the file when the doorbell is ringing? You'll have to be quick. 
{
                    "functionClass": "doorbell",
                    "lastUpdateTime": 1697816900403,
                    "value": "not-ringing"
                },

**Comment by aurochsen** [comment]
I believe this is it, I've run it a few times while ringing and a few without. When ringing the doorbell attribute changed to "value": "button-1" and swaps back to "not-ringing" when its done. Surprisingly appears to stay in ringing status for a few seconds so might not have to completely dos the api for this to be effective.  
[apioutput2.json](https://github.com/jdeath/Hubspace-Homeassistant/files/13061814/apioutput2.json)

**Comment by jdeath** [comment]
That file is empty, but "button-1" seems to make sense and I saw that in the list of options. Maybe you can pair multiple doorbells to one base station, so it tells you the first one is ringning. 

I probably will not get to this for a while. But should be able to make a "light" that turns on when the button is pressed. 

To add yourself (might be quicker!) Look in light.py, Take the hubspacelock definition as a starting point and copy it as HubspaceDoorBell. To check if light is on, see if "doorbell" functionclass is equal "button-1" (or maybe not equal to "not-ringing") in the is_on function. Then call this new doorbell entity when model is "HB-3015-00" in the add_entity function.

You will probably have to increasing the scan_interval and base_interval to ~10s for it to get picked up.

**Comment by aurochsen** [comment]
Yep you can add multiple buttons so makes sense. I'll tinker with it to see
if I can figure it out without breaking everything else. I might get lucky.
Thanks

**Comment by Expl0dingBanana** [comment]
@aurochsen I am going to close this issue as it seems to be related to polling time. Please re-open the issue if you need any help!
