### ISSUE TITLE
[device add request] hubspace puff surface mount

### ISSUE THREAD

**Issue by wafflecopters** [jdeath/Hubspace-Homeassistant#58]
[log.txt](https://github.com/jdeath/Hubspace-Homeassistant/files/13197033/log.txt)

**Comment by jdeath** [comment]
Hopefully it turned off/on without any changes? Manualy replace your light.py in custom_components/hubspace with the latest light.py in the repo. On/off/color/brightness/colortemp should work.

**Comment by Expl0dingBanana** [comment]
Can you test with #86 and see if this solves your issue?

During testing, you will move the repo to `https://github.com/Expl0dingBanana/Hubspace-Homeassistant`. Once the PR is merged, you will need to move it back to this @jdeath 's repo.

**Comment by Expl0dingBanana** [comment]
I believe this has been resolved with 3.0. Please re-open the issue if the problem persists

**Comment by wafflecopters** [comment]
I have updated and now am unable to change the color (it fails in the UI or in an automation). When I do it in the home assistant UI I get:

Failed to call service light/turn_on. 400, message='Bad Request', url=URL('https://api2.afero.net/v1/accounts/<accountID>/metadevices/<deviceID>')

**Comment by Expl0dingBanana** [comment]
Can you provide the logs from Settings -> System -> Logs? That error message is unexpected as thats not how it should be interacting with hubspace. This is a typical message when interacting with an entity fails:

```Failed to call service light/turn_on. 403, message='Forbidden', url=URL('https://api2.afero.net/v1/accounts/blah/metadevices/f06be777-eddc-426d-8fff-b5f5d316c63d/state')```

**Comment by Expl0dingBanana** [comment]
I was reviewing `log.txt` and see that there are two entries for the puff surface mount. Do you have two of these devices?

**Comment by wafflecopters** [comment]
I do have 2 of them.

**Comment by wafflecopters** [comment]
This is when I attempted to turn on the light by pressing the red color button in the home assistant UI:

[547464077248] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2731, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2774, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 999, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1071, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 628, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/config/custom_components/hubspace/light.py", line 452, in async_turn_on
    await self._hs.set_device_states(self._child_id, states_to_set)
  File "/usr/local/lib/python3.12/site-packages/hubspace_async/connection.py", line 252, in set_device_states
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 1070, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api2.afero.net/v1/accounts/c8fa917f-8d47-4304-bc09-9b6e727c494f/metadevices/12397043-d1f9-4ede-8beb-609824c4ed6e/state')

**Comment by wafflecopters** [comment]
Also, no idea if relevant, but the 2 lights flicker ever so subtlely when they are *off*

**Comment by Expl0dingBanana** [comment]
I believe this has been fixed with #91 . Please review the testing instructions within that PR and post any comments within that PR.

**Comment by Expl0dingBanana** [comment]
Closing this issue as it was addressed with #91 .
