### ISSUE TITLE
Error while setting up Hubspace

### ISSUE THREAD

**Issue by djqpaz** [jdeath/Hubspace-Homeassistant#6]
Hey Jdeath, 

Getting the error below... all are devices are non functioning.. tried restarting...but no dice. 

Logger: homeassistant.components.light
Source: custom_components/hubspace/light.py:62
Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: July 10, 2022, 11:17:49 PM (1 occurrences)
Last logged: July 10, 2022, 11:17:49 PM

Error while setting up hubspace platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/hubspace/light.py", line 62, in setup_platform
    _LOGGER.debug("Switch on Model " + model )
TypeError: can only concatenate str (not "NoneType") to str

**Comment by jdeath** [comment]
I think their API sometimes returns crap data. Try removing the "custom_components.hubspace: debug" line from the logger: section of configuration.yaml 

Mine is working fine (just updated home assistant too). I am working on adding transformers, so I'll try to put extra checks in for bad data.

**Comment by jdeath** [comment]
Hmm. I'm having errors now too. Hopefully just the API is messed up.

**Comment by whundahl** [comment]
Having the Same issue. It works well for up to 3 entities, but after that the program chokes if trying to add more than 3. 

`light:
  - platform: hubspace
    username: HUBSPACE_USSER
    password: HUBSPACE_SECRET
    friendlynames:
    - 'Ceiling'
    - 'Entryway'
    - 'Sinklight'
    - 'Barlamp'
    - 'hallway'
    - 'Bathroom1'
    - 'Bathroom2'`

**Comment by jdeath** [comment]
Can you confirm each one works fine one-by-one? That is strange. Perhaps you are hitting the API too often with so many lights.

Perhaps edit line 21 and 22 in light.py to be 120 or 180 seconds.
