### ISSUE TITLE
Document new device / getting started a bit better (or: no Device bug?)

### ISSUE THREAD

**Issue by zyphlar** [jdeath/Hubspace-Homeassistant#61]
I hunted around for a little too long and finally realized my string lights showed up as `light.string` under Entities and not attached to the `Den` Area that I'd marked it as, and even after confirming that I can turn it on/off and assign it to an Area and enable it, it's still not a Device showing up on the Overview page and I had to manually edit my Overview dashboard, edit the Den pane, and add the entity to it. Maybe it's just me being a noob, but at the very least "the device should show up as light.<devicename> in Entities, if not check the logfile at this location" in the Readme would be enough to get me on the right track.

Thanks for all the excellent work you've done making this work!

**Comment by jdeath** [comment]
Please do a PR with an edited readme to make it more clear. You can do it all from the web, no coding required. Clone the repo, edit the readm, then submit a PR when you are happy with the change. I will review and add it in. Thanks
