### ISSUE TITLE
Light Color Temperature lost after upgrade

### ISSUE THREAD

**Issue by pbjfarm** [jdeath/Hubspace-Homeassistant#62]
When running anything newer than 1.93 my light entity turns into a simple on/off - without the controls for color temperatur. Downgrading to 1.93 bring the controls back.

I think I have a Driskol fan...still looking for the manual - but it appears to not report a model number.

TestHubspace.py output: https://pastebin.com/NGVwUzx3

**Comment by jdeath** [comment]
Thanks for the output. I tried a better way to identify items that do not return the model number, I obviously goofed something with the light. Fans with lights are hard to handle! I will take a look. Does the fan work properly still? It may take me a couple days, no harm in going to 1.93, as new functionality has been added.

**Comment by jdeath** [comment]
Ok. Think I got it. To test it out, first update to the latest version using HACS. Then download the Hubspace.py file from the repo and replace the one in custom_components/hubspace/   . Hopefully it will work. 

If it works, I will make a new release. I just do not want to make a release if this fix does not work

**Comment by pbjfarm** [comment]
Perfect! Color-temp controls are back. I deleted and re-discovered a couple of times, just to make sure - and everything consistently appeared.

Thank you!

**Comment by jdeath** [comment]
Great. Closed with release v1.96
