### ISSUE TITLE
Support for a new model, fix existing model

### ISSUE THREAD

**Issue by z062007vette** [jdeath/Hubspace-Homeassistant#64]
I’m wondering if support could be added for the following devices.
https://www.homedepot.com/p/Defiant-Smart-Outdoor-4-ft-6-Outlet-Power-Stake-Powered-by-Hubspace-LH-7-1-4FT/324832048 - Model#: LH-7-1-4FT

Additionally, Model HPPA51CWB seems to have been converted to a 2 plug output and I have the 1 plug variant. Unsure why I cannot get this to show up. I might be REALLY bad at following instructions here. Not sure if I should be using light, power-outlet, or outlet in the config yaml. 

Output of Testhubspace.py attached. 

[2023-11-23-LH-7-1-4FT-z062007vette.json](https://github.com/jdeath/Hubspace-Homeassistant/files/13520255/2023-11-23-LH-7-1-4FT-z062007vette.json)

Thank you in advance.

**Comment by jdeath** [comment]
Thanks for the output. Your model "HPPA51CWB" should already be supported as a single plug model. Not sure why it is not showing up. Can you try specifying the friendly name and not rely on the autoscan.

The config yaml should be light: , just like shown in the documentation. Everything is a light in this integration, including locks, lights, outlets, Follow it exactly.

**Comment by z062007vette** [comment]
This issue was totally my HA install.... I had it as a VM in Unraid, but doubt that install was right. I've now moved to an RPI that was no longer being use for Octoprint, and now see the two lights. Thank you and sorry for all the back an forth. Learned a lot through this just. Thank you for all your work on this. I'll see if I can (skills provided) help with the autoscan. Cheers!
