### ISSUE TITLE
Hubspace integration failing to discover "entities" in my Account

### ISSUE THREAD

**Issue by HyperlinkNetworking** [jdeath/Hubspace-Homeassistant#67]
Hi there, trying to configure Hubspace integration via HACS on my Home Assistant VM. I've added the following snippet to my "configuration.yaml" file, I've also attached any error/warning logs related to the Hubspace integration.

I've also tried using friendly names and room names, this had no altering effects. according to the documentation it is not necessary and the lock should be discovered as a light entity automatically..

I have restarted Home Assistant and I'm currently running the latest integration v1.99.

```
light:
  - platform: hubspace
    username: Example@Email.com
    password: Password1234
    debug: true
```

This is the only related warning I could pull up, However I think that's just something that you have to change before that feature is removed.

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1520
First occurred: 9:55:32 PM (2 occurrences)
Last logged: 9:55:32 PM
Entity None (<class 'custom_components.hacs.update.HacsRepositoryUpdateEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <UpdateEntityFeature.INSTALL|PROGRESS|RELEASE_NOTES: 21>, please create a bug report at https://github.com/hacs/integration/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
```

I did get one brief error in my logs, but doesn't seem to be appearing anymore..

```
2024-01-07 21:33:56.910 ERROR (MainThread) [homeassistant.components.light] Error while setting up hubspace platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hubspace/light.py", line 155, in setup_platform
    for childId in children:
TypeError: 'NoneType' object is not iterable
```
I'm specifically trying to add a Hubspace lock and plug as "light" entities to HA. 

I greatly appreciate your time.

**Comment by jdeath** [comment]
Please use the Home Assistant forum for help. This is for issues, not for help setting up the integration. You probably have a password issue, follow all the troubleshooting tips and type the friendlynames exactly. The above error looks like you specified a room name.

It is possible that your devices are not supported yet, but I would expect they would still show up.
