### ISSUE TITLE
Lost color control on CD44bRGBW11W 

### ISSUE THREAD

**Issue by Adanufgail** [jdeath/Hubspace-Homeassistant#68]
Hello,

I previously opened #50 about the CD44bRGBW11W. It looks like the same thing that happened in #62 has also happened to this model as well. 

Here is the current TestHubspace output: https://pastebin.com/jQ4j7EMH

I am utilizing version 1.99 from HACS.

**Comment by jdeath** [comment]
Try the new version 2.00

**Comment by Adanufgail** [comment]
Yep, that fixed it! Thanks for the quick update!
