### ISSUE TITLE
Add CF2003 Fan

### ISSUE THREAD

**Issue by jdeath** [jdeath/Hubspace-Homeassistant#79]
manually download the latest light.py. Be sure to add your friendlyname into the YAML. Hopefully the fan/light will work, but it probably wont..

**Comment by maekse** [comment]
here's the output of TestHubspace.py: [CF2003.json](https://github.com/jdeath/Hubspace-Homeassistant/files/15210196/CF2003.json)
I can control the fan and light fairly reliably by manually sending commands via hubspace: Send Command operation, but naturally that's not ideal.

**Comment by jdeath** [comment]
Did the latest light.py not work?

**Comment by maekse** [comment]
it worked great, actually. thank you!
