### ISSUE TITLE
Attempting to set up 76278, 37278 fan

### ISSUE THREAD

**Issue by Legitthe** [jdeath/Hubspace-Homeassistant#8]
I am trying to set up the above model fan, I am able to grab the light, but not yet able to control it, but its state is updated each time I toggle on/off. I ahve the attributes spit out if that would help.

**Comment by jdeath** [comment]
Yes, please provide the attributes when the light is off/on and fan is off/on. Hopefully it works just like '52133, 37833', but who knows. 

If you want to do quick check, replace '52133, 37833' in the code (line 86 and line 147) with your model and see if it just works.

**Comment by jdeath** [comment]
Closing as I believed fixed. Please reopen if does not work
