### ISSUE TITLE
Request support for Tager fans - N383-MBK (60") and N383C-MBK (72")

### ISSUE THREAD

**Issue by acibo** [jdeath/Hubspace-Homeassistant#87]
When time permits please add support for Tager fans N383B-MBK (60" fan) and N383C-MBK (72" fan).  I requested elsewhere but was directed to the readme which says to open a new issue.  I apologize for adding the request in another thread of requests.
[Hubspace.log](https://github.com/user-attachments/files/16378586/Hubspace.log)

**Comment by jdeath** [comment]
Try the fork of the project below. @Expl0dingBanana has been working to make discovery of devices automatic. If his fork does not work, he can use the dump you posted to add it. Note this fork gets setup from the UI.

`https://github.com/Expl0dingBanana/Hubspace-Homeassistant`

This fork will soon get merged, once fully tested

**Comment by acibo** [comment]
Thank you very much.

 

Slick update.  After getting prompted for the username/password of the hubspace account everything auto-configured correctly.

 

I appreciate the help and the work you folks are doing.

 

Kevin

**Comment by Expl0dingBanana** [comment]
@acibo glad it worked for you! After a few issues are fixed, #86 will be merged into this repo and you will need to update the repo location.

**Comment by Expl0dingBanana** [comment]
Thias has been resolved with 3.0.0

**Comment by acibo** [comment]
Good afternoon, I switched back to the jdeath repository after removing Hubspace from Home Assistant. After downloading and installing version 3.0, it auto configures, showing me the four fans after entering my username and password, but the buttons to turn them on are greyed out.Is there something else I need to be doing to have this work with the mainstream repository?Thank you,KevinOn Jul 29, 2024, at 3:37 PM, Christopher Dohmen ***@***.***> wrote:﻿
@acibo glad it worked for you! After a few issues are fixed, #86 will be merged into this repo and you will need to update the repo location.

**Comment by Expl0dingBanana** [comment]
The latest release (3.0.3) should have the fix for fans showing as
unavailable. Let me know if pulling in the latest does not fix the issue
