### ISSUE TITLE
Offlice Devices Show "On" as was their last state

### ISSUE THREAD

**Issue by ahahamyan** [jdeath/Hubspace-Homeassistant#90]
Hello, just updated to the latest refactor (3.0) and it looks great. But my devices which are offline (shows same in the Hubspace mobile app) show with a state of "on" in HA which was the last state on Hubspace cloud when my devices were powered off. These bulbs are for my outside lighting and I don't power them up until sunset (all automated via HA) This was previously working fine prior to the refactor (There was a lightning bolt, etc.. indicating offline) in HA. It looks like that is gone with latest changes. 

![Screen Shot 2024-08-01 at 12 23 31 PM](https://github.com/user-attachments/assets/102b6c12-1b8e-48e7-916d-f457143d530a)

Please add that feature back on top of 3.0 (very nice work by the way). Thank you. 

I am running

Core
2024.7.4
Supervisor
2024.06.2
Operating System
12.4
Frontend
20240710.0

**Comment by Expl0dingBanana** [comment]
Let me take a look at this. I know HA has the ability specify `available` so I can set that property if HA reports it as such.

**Comment by Expl0dingBanana** [comment]
I believe this has been fixed with #92  as it ensures a user cannot interact with an unavailable device . Please review the testing instructions within that PR and post any comments within that PR.

**Comment by ahahamyan** [comment]
Thanks. I downloaded the 3.0.2 Beta and installed. It is working as expected now. The devices show as unavailable.

**Comment by Expl0dingBanana** [comment]
Awesome! I am going to close this issue as it appears to be resolved. Please create a new issue if it happens again.
