### ISSUE TITLE
Fan is unavailable in HA integration 3.02 but available in Hubspace

### ISSUE THREAD

**Issue by kevanrmueller** [jdeath/Hubspace-Homeassistant#93]
Fan is showing as unavailable in Home Assistant. Was available in previous version. I can still access in Hubspace app

[_dump_hs_devices.json](https://github.com/user-attachments/files/16464217/_dump_hs_devices.json)

**Comment by bobhogs** [comment]
I also have a ceiling fan and the fan is no longer recognized with the same model number as in your json. Hopefully this will be sorted out fairly quick as far as these things go.

**Comment by Expl0dingBanana** [comment]
I believe this has been fixed with #93. Please review the testing instructions within that PR and post any comments within that PR.
