### ISSUE TITLE
Devices seen but greyed out in new version

### ISSUE THREAD

**Issue by totalhavoc** [jdeath/Hubspace-Homeassistant#96]
Pretty sure they just need to be updated by you guys. Here are the files:
[_dump_hs_raw.json](https://github.com/user-attachments/files/16470900/_dump_hs_raw.json)
[_dump_hs_devices.json](https://github.com/user-attachments/files/16470902/_dump_hs_devices.json)

**Comment by totalhavoc** [comment]
NVM... manually updated the fan.py file with the latest version and everything seems to be working. Just need to test a few automations but I think I'm good there too

**Comment by Expl0dingBanana** [comment]
@totalhavoc Please close the issue if everything is working as expected. Thanks!

**Comment by jonathjon** [comment]
> NVM... manually updated the fan.py file with the latest version and everything seems to be working. Just need to test a few automations but I think I'm good there too

I just got this installed yesterday and my fan is grayed out as well.  How did you manually update the fan.py file?  The light on the fan works as it should but I cant control the fan at all.  Thanks!

**Comment by Expl0dingBanana** [comment]
@jonathjon Make sure you are on the latest version (v3.0.4 as of writing) and that should solve your issue.
