### ISSUE TITLE
Hubspace Transformer 

### ISSUE THREAD

**Issue by oprey123** [jdeath/Hubspace-Homeassistant#97]
Hubspace Transformer not working any longer in new version.  I uninstalled hubspace integration in hacs, deleted the custom configuration, redownloaded hubspace and the integration, logged in via UI, zone 1 2 and 3 show up but unavailable.

attached required files.

[_dump_hs_raw.json](https://github.com/user-attachments/files/16471076/_dump_hs_raw.json)
[_dump_hs_devices.json](https://github.com/user-attachments/files/16471077/_dump_hs_devices.json)

**Comment by Expl0dingBanana** [comment]
Can you provide the anonymized dump from the troubleshooting instructions?
That should help keep it working moving forward

It appears one of the sensors caused the issue as I took some guesses on
what it looked like

**Comment by oprey123** [comment]
I'll pull it now no problem.  Thank you

**Comment by oprey123** [comment]
[home-assistant_hubspace_2024-08-02T13-50-53.629Z.log](https://github.com/user-attachments/files/16471242/home-assistant_hubspace_2024-08-02T13-50-53.629Z.log)
This is from the debug log in the intergration

**Comment by Expl0dingBanana** [comment]
Can you provide the file _dump_hs_devices.json?
Instructions @ https://github.com/jdeath/Hubspace-Homeassistant/blob/main/README.md#through-the-ui

**Comment by oprey123** [comment]
[_dump_hs_raw.json](https://github.com/user-attachments/files/16472032/_dump_hs_raw.json)
[_dump_hs_devices.json](https://github.com/user-attachments/files/16472035/_dump_hs_devices.json)

**Comment by Expl0dingBanana** [comment]
Sorry, I missed the original post that already had this info.  I hate reading on my phone :(

**Comment by oprey123** [comment]
No problem at all, I originally posted just the dump then realized that you needed particular files so I edited my original post, probably after you saw it and replied to the original dump.

**Comment by Expl0dingBanana** [comment]
I am currently looking into this. There are a few things at play that I see:

 * Sensors need to determine if they are int / string and explode if the incorrect type (one of the exceptions)
 * On/Off are not correctly updating due to how states are handled
 * Entity creation seems to be making multiple of the same zones

**Comment by Expl0dingBanana** [comment]
I believe this should be fixed with #98. The PR has instructions for installing the test code. Please let me know if the issue persists after the update!

**Comment by oprey123** [comment]
Works great thank you.  All zones now working, metrics displaying correctly. 
![Screenshot 2024-08-02 180046](https://github.com/user-attachments/assets/1da16a0c-dd82-4cb2-8700-5c0605043e2b)

**Comment by oprey123** [comment]
Thanks closing
